In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.precision', 4)
pd.set_option('display.float_format',  '{:24}'.format)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 100)

In [2]:
def corregirColumna(df, col):
    df1 = df[col].astype(str).copy()
    df1 = df1.apply(lambda x: list(x.split(".",1))[0])
    return df1

In [3]:
file = 'C:/Users/N1567011/OneDrive - Liberty Mutual/Documents/Proyectos/Chile/Khalil Kawssan/Comparacion/base_ambas_companias_aseg.csv'
dfs = pd.read_csv(file, sep = ';', 
                  encoding='ISO-8859-1',
                  low_memory=False, 
                  error_bad_lines=False, warn_bad_lines=False, nrows=500000, dtype=str)
dfs.columns = dfs.columns.str.upper()
dfs

,SSEGURO,CAGENTE,CAGRSEG,POLIZA,ITEM,INI_VIG,FIN_VIG_ORIG,FIN_VIG_ACT,DIAS_VIGENTE,DIAS_SUSCRITOS,VEH_CMARCA,VEH_CMODELO,VEH_CLASE,VEH_CVERSION,TVERSION,USO,VEH_ANO,PATENTE,VEH_CTIPO,VEH_TIPO,TMARCA,TMODELO,NUM_MOTOR,CORREDOR_RUT,CORREDOR,COD_PRODUCTO,PRODUCTO,COD_PLAN,PLAN,DEDUCIBLE,DEDUCIBLE_INI,CONTRATANTE_RUT,CONTRATANTE_NOMBRE,FLOTA1,NRO_MASIVO,PRIMA,PRIMA_TARIFA,DESCUENTO,COMISION,PRIMA_FINAL,COD_ENDOSO,TDESCRIP,ENDOSO_AGRUP,NOMBRE_CONVENIO,FLOTA_CONVENIO,SUCURSAL,COD_SUCURSAL1,SUMA_ASEG_RC,ORIGEN,ASEGURADO_RUT,ANO_REF_INI,LLAVE,NUM_ITEMS_CONTRA,FLOTA_CONTRA,COD_CONVENIO,FLOTA,COD_SUCURSAL,LC_MODEL,LC_MODEL_DEF,MES_REF_INI,PRIMA_RECIBO,PRIMA_RECIBO_FINAL,COB_INI,COB_FIN,FECHA_COTRENOV,PLAN_DESC,TIPO_PLAN,ANTERIOR,NUM_ITEMS,COD_MARCA_P,COD_MODELO_P,COD_TIPO_P,CANAL,DURACION_PLAN,ORIGEN_MARCA,ANTIG_VEHICULO,PT_RO,DATE_UPDATE,FORMA_PAGO_INI,FORMA_PAGO_FIN,METODO_PAGO,RAZON_CUOTAS,TUVO_PT,FORMA_PAGO_DEF,MOTIVO_CANCEL_ANUL,TIPO_PERS,SEXO,NACIONALIDAD,SEXO_ASEGURADO,FECHA_NACIMIENTO,EDAD_ASEGURADO
0,2618871,00995032,NaN,6287875,1,27/02/2013,27/02/2014,27/02/2014,365,365,14,510,L,14510002,OPTRA LS NB 1.6 16V MT AC,PARTICULAR,2004,XJ9745,1,AUTOMOVIL,CHEVROLET,OPTRA,F16D3075307K,99061000,VTA DIRECTA VI?A DEL MAR LIBERTY SEGUROS SA,426,Vehiculo Liberty 1,1,CLUB PARTICULAR,10,0,6071465,VALENZUELA ULLOA GERARDO,0,0,12,7.92,0,0,8.35,281,SE DEJA CONSTANCIA QUE SE MODIFICA ASEGURADO Y SE REBAJA PRIMA NETA EN UF 0.26 POR INCLUSION DE ...,AJUSTE,SIN AGRUPACION,NaN,PROVIDENCIA,00000032,500,LIBER,NaN,2013,6071465-2013,2,0,0,0,32,NaN,NaN,NaN,12,11.74,8532,8532,21JAN2013:12:08:13,RC + DM + RO,FULL,NO,1,NaN,NaN,NaN,TRADICIONAL,1 ANO,ESTADOS UNIDOS,9,0,05/06/2022,CUPONERA,NaN,CUPONERA,NaN,NaN,CUPONERA,NaN,PJur,NaN,NaN,NaN,NaN,NaN
1,3591452,07965010,NaN,6383242,3,05/04/2014,05/04/2015,05/04/2015,365,365,62,115,L,62115001,YARIS GL,PARTICULAR,2010,CDRW29,1,AUTOMOVIL,TOYOTA,YARIS,2NZ5111394,79933990,SOC CORREDORES SEGSLOTA ASOCIADOS LTDA,760,Vehiculo Individual,1,CLUB PARTICULAR,0,0,5892949,MULLER WOLLMANN DORIS FANNY,0,0,15.44,27.58,0,0.15,15.44,802,"SE MODIFICA ASEGURADO DE ITEM # 3.- DEBE DECIR:\nRIGE A FAVOR DE NICOLE FARJI MULLER , RUT: 18.6...",AJUSTE,SIN AGRUPACION,NaN,HENDAYA,00000010,1000,LIBER,NaN,2014,5892949-2014,3,0,0,0,10,NaN,NaN,NaN,15.44,15.44,96172,96172,13MAR2014:16:54:48,RC + DM + RO,FULL,NO,3,NaN,NaN,NaN,TRADICIONAL,1 ANO,JAPON,4,0,05/06/2022,CUPONERA,CUPONERA,CUPONERA,Redocumentacion,NaN,CUPONERA,NaN,PJur,NaN,NaN,NaN,NaN,NaN
2,3476389,07685025,3204,6372976,1,29/01/2014,29/01/2015,29/01/2014,0,365,48,516,L,48516003,508 ACTIVE AT 1.6,COMERCIAL,2012,DYSV69,1,AUTOMOVIL,PEUGEOT,508,10JBEG3078126,77191070,BANCO CHILE,674,Banco Chile Plataforma Empresa,209,BANCHILE DM (LIVIANO COMERCIAL),5,5,76232750,SOC. DE TRANSPORTES CRISTOBAL LTDA.,0,120000006388449,16.85,16.85,-1.09,0.12,16.85,365,"Se anula por error en producto de carga, se volvera a emitir",ANULACION,BANCHILE CONTINUIDAD DE RIESGO,0,BANCA SEGUROS,00000025,1000,LIBER,NaN,2014,76232750-2014,1,0,3204,0,25,NaN,NaN,NaN,16.85,0,10385,10385,27JAN2014:12:22:50,RC + DM + RO,FULL,NO,1,NaN,NaN,NaN,BANCA,1 ANO,FRANCIA,2,0,05/06/2022,NaN,NaN,NaN,NaN,NaN,AVISO CUOTA,NaN,PJur,NaN,NaN,NaN,NaN,NaN
3,9967651,09947380,4284,6894832,92,02/01/2019,16/08/2019,16/08/2019,226,226,39,8,P,39008001,ACONCAGUA LO-915,DESCONOCID,2012,DWZB77,22,BUS,MERCEDES BENZ,LO915,904957U0931755,79619240,FRANCISCO RODRIGUEZ PRODUCTORA DE SEGUROS LTDA,998,RC en Exceso Colectivo,28,RC EN EXCESO,0,0,96860520,SOCIEDAD COMERCIAL E INMOBILIARIA LA CUMBRE S A,1,0,6.49,4.02,0,0.235,6.49,100,NaN,NUEVA PROD,LOCOMOCION COLECTIVA,1,VIÑA DEL MAR,00000380,5000,LIBER,NaN,2019,96860520-2019,127,1,4284,1,**,NaN,NaN,NaN,6.492,6.492,6505,6505,22JAN2019:10:28:28,RC,RC_E,NO,116,NaN,NaN,NaN,TRADICIONAL,MENOS 1 ANO,ALEMANIA,7,0,05/06/2022,CUPONERA,CUPONERA,PAGO CONTADO,Redocumentacion,NaN,CUPONERA,NaN,PJur,NaN,NaN,NaN,NaN,NaN
4,9751333,08954010,NaN,6953759,1,15/11/2018,15/11/2019,15/11/2019,365,365,14,531,P,14531003,FRR 1119 E4,COMERCIAL,2011,DJRW78,20,CAMION,CHEVROLET,FRR,4HK1905786,77371990,SECURITY,988,Traspaso Cartera Libre,26,LIBRE PESADO,0,0,93764000,MOLINO BALMACEDA S A,0,7429426,34.1,40.54,-6.46,0.13,34.1,802,mediante el presente endoso se mod asegurado sin mov de prima,AJUSTE,SIN AGRUPACION,NaN,HENDAYA,00000010,700,LIBER,NaN,2018,93764000-2018,5,1,0,0,10,NaN,NaN,NaN,34.1,34.1,96164,96164,10JAN2019:15:21:30,RC + DM + RO,FULL,NO,1,NaN,NaN,NaN,TRADICIONAL,1 ANO,ESTADOS UNIDOS,7,0,05/06/2022,PAGO CONTADO,PAGO CONTADO,CUPONERA,Redocumentacion,NaN,PAGO CONTADO,NaN,PJur,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,2280259,07600010,NaN,6258485,1,08/09/2012,08/09/2013,28/05/2013,262,365,25,218,L,25218001,CR-V EX 2.4 AUT. 4X4,PARTICULAR,2010,CDJS52,5,JEEP,HONDA,CRV,K24213745344,77508900,THB CHILE CORREDORES SEGUROS SA #THB CHILE S,426,Vehiculo Liberty 1,1,CLUB PARTICULAR,5,5,6799193,YANY SAYEH MARIA CRISTINA,0,14792,16.47,16.47,0,0.13,16.47,325,NaN,CANCELACION,SIN AGRUPACION,NaN,HENDAYA,00000010,500,LIBER,6799193,2012,6799193-2012,1,0,0,0,10,NaN,NaN,NaN,16.47,6.45,10385,10385,20SEP2012:10:37:35,RC + DM + RO,FULL,NO,1,NaN,NaN,NaN,TRADICIONAL,1 ANO,JAPON,2,0,05/06/2022,PAGO CONTADO,PAGO CONTADO,AVISO CUOTA,Redocumentacion,NaN,PAGO CONTADO,NaN,PNat,0,C,M,28/08/1953,59
499996,1585764,07600010,NaN,6181073,1,08/09/2011,08/09/2012,08/09/2012,366,366,25,218,L,25218001,CR-V EX 2.4 AUT. 4X4,PARTICULAR,2010,CDJS52,5,JEEP,HONDA,CRV,K24213745344,77508900,THB CHILE CORREDORES SEGUROS SA #THB CHILE S,426,Vehiculo Liberty 1,1,CLUB PARTICULAR,5,5,6799193,YANY SAYEH MARIA CRISTINA,0,14792,16.47,18.5,-2.03,0.13,16.47,100,NaN,NUEVA PROD,SIN AGRUPACION,NaN,HENDAYA,00000010,500,LIBER,6799193,2011,6799193-2011,1,0,0,0,10,NaN,NaN,NaN,16.47,16.47,10385,10385,15SEP2011:16:26:25,RC + DM + RO,FULL,NO,1,NaN,NaN,NaN,TRADICIONAL,1 ANO,JAPON,1,0,05/06/2022,AVISO CUOTA,AVISO CUOTA,AVISO CUOTA,NaN,NaN,AVISO CUOTA,NaN,PNat,0,C,M,28/08/1953,58
499997,900194642,07130024,5397,61007845,1,15/12/2017,15/12/2019,15/12/2019,730,730,38,414,L,38414001,NEW CX5 2.0 AT,PARTICULAR,2018,FACT00,5,JEEP,MAZDA,CX5,PE31111430,76499669,DERCO,969,Derco,653,DERCO PARTICULAR MIGRACION,5,5,6799193,YANY SAYEH MARIA CRISTINA,0,NaN,16.165,16.165,0,0.24,16.165,100,NaN,NUEVA PROD,MIGRACION DERCO,0,RETAIL,00000024,1500,LIBER,6799193,2017,6799193-2017,1,0,5397,0,24,NaN,NaN,NaN,16.17,16.17,108463,108463,09APR2019:21:04:45,RC + DM + RO,FULL,EX PENTA,1,NaN,NaN,NaN,DEALERS,2 ANOS,JAPON,-1,0,05/06/2022,PAC,PAC,NaN,NaN,NaN,AVISO CUOTA,NaN,PNat,0,C,M,28/08/1953,64
499998,903676330,07130024,4447,61136831,1,15/12/2019,15/12/2020,15/12/2020,366,366,38,414,L,38414001,NEW CX5 2.0 AT,PARTICULAR,2018,FACT00,5,JEEP,MAZDA,CX5,PE31111430,76499669,DERCO,969,Derco,516,DERCO CON EXCLUSIVIDAD,5,5,6799193,YANY SAYEH MARIA CRISTINA,0,NaN,16.13,16.13,0,0.24,16.13,100,NaN,NUEVA PROD,RENOV EXP DERCO,0,RETAIL,00000024,1500,LIBER,6799193,2019,6799193-2019,1,0,4447,0,24,NaN,NaN,NaN,16.13,16.13,108460,108460,25NOV2019:16:26:54,RC + DM + RO,FULL,NO,1,NaN,NaN,NaN,DEALERS,1 ANO,JAPON,1,0,05/06/2022,PAC,PAC,NaN,NaN,NaN,AVISO CUOTA,NaN,PNat,0,C,M,28/08/1953,66
499999,905498433,07130024,4447,61313038,1,15/12/2020,15/12/2021,12/11/2021,332,365,38,414,L,38414001,NEW CX5 2.0 AT,PARTICULAR,2018,FACT00,5,JEEP,MAZDA,CX5,PE31111430,76499669,DERCO,969,Derco,516,DERCO CON EXCLUSIVIDAD,5,5,6799193,YANY SAYEH MARIA CRISTINA,0,NaN,16.13,16.13,0,0.24,16.13,376,POR VENTA,CANCELACION,RENOV EXP DERCO,0,RETAIL,00000024,1500,LIBER,6799193,2020,6799193-2020,1,0,4447,0,24,NaN,NaN,NaN,16.13,14.67,108460,108460,16NOV2020:10:04:57,RC + DM + RO,FULL,NO,1,NaN,NaN,NaN,DEALERS,1 ANO,JAPON,2,0,05/06/2022,PAC,PAC,NaN,NaN,NaN,AVISO CUOTA,NaN,PNat,0,C,M,28/08/1953,67

In [4]:
dfs['MOTIVO_CANCEL_ANUL'].value_counts()

Series([], Name: MOTIVO_CANCEL_ANUL, dtype: int64)

In [5]:
dfs.loc[dfs['ORIGEN']=='LIBER','ORIGEN'] = 'LIBERTY'
dfs['KEY'] = dfs['POLIZA'].astype(str) + '-' + dfs['ITEM'].astype(str) + '-' + dfs['ORIGEN'].astype(str)

In [7]:
dfs['FECHA_NACIMIENTO'] = pd.to_datetime(dfs['FECHA_NACIMIENTO'], format='%d/%m/%Y', errors = 'coerce').dt.strftime('%Y-%m-%d')

In [8]:
dfs['FIN_VIG_ORIG'] = pd.to_datetime(dfs['FIN_VIG_ORIG'], format='%d/%m/%Y', errors = 'coerce').dt.strftime('%Y-%m-%d')
dfs['INI_VIG'] = pd.to_datetime(dfs['INI_VIG'], format='%d/%m/%Y', errors = 'coerce').dt.strftime('%Y-%m-%d')
dfs['FIN_VIG_ACT'] = pd.to_datetime(dfs['FIN_VIG_ACT'], format='%d/%m/%Y', errors = 'coerce').dt.strftime('%Y-%m-%d')
dfs['DATE_UPDATE'] = pd.to_datetime(dfs['DATE_UPDATE'], format='%d/%m/%Y', errors = 'coerce').dt.strftime('%Y-%m-%d')
dfs['FECHA_COTRENOV'] = pd.to_datetime(dfs['FECHA_COTRENOV'],format="%d%b%Y:%H:%M:%S", errors = 'coerce').dt.strftime('%Y-%m-%d')

In [9]:
dfs.isna().sum()

SSEGURO             195647
CAGENTE             195647
CAGRSEG             342403
POLIZA                   0
ITEM                     0
                     ...
NACIONALIDAD         57387
SEXO_ASEGURADO       34609
FECHA_NACIMIENTO     31521
EDAD_ASEGURADO       31521
KEY                      0
Length: 92, dtype: int64

In [10]:
#dfs.info(verbose=True)

In [11]:
file = 'C:/Users/N1567011/OneDrive - Liberty Mutual/Documents/Proyectos/Chile/Khalil Kawssan/Comparacion/APTP_BASE_AMBAS_COMPANIAS_ASEG.csv'
dfp = pd.read_csv(file, sep=';',encoding='utf-8-sig', low_memory=False, dtype=str, 
                 error_bad_lines=False, 
                 warn_bad_lines=False,
                  nrows=500000,
                lineterminator='\n')

In [12]:
dfp['KEY'] = dfp['POLIZA'].astype(str) + '-' + dfp['ITEM'].astype(str) + '-' + dfp['ORIGEN'].astype(str)
dfp.head()

,SSEGURO,CAGENTE,CAGRSEG,POLIZA,ITEM,INI_VIG,FIN_VIG_ORIG,FIN_VIG_ACT,DIAS_VIGENTE,DIAS_SUSCRITOS,VEH_CMARCA,VEH_CMODELO,VEH_CLASE,VEH_CVERSION,TVERSION,USO,VEH_ANO,PATENTE,VEH_CTIPO,VEH_TIPO,TMARCA,TMODELO,NUM_MOTOR,CORREDOR_RUT,CORREDOR,COD_PRODUCTO,PRODUCTO,COD_PLAN,PLAN,DEDUCIBLE,DEDUCIBLE_INI,CONTRATANTE_RUT,CONTRATANTE_NOMBRE,FLOTA1,NRO_MASIVO,PRIMA,PRIMA_TARIFA,DESCUENTO,COMISION,PRIMA_FINAL,COD_ENDOSO,TDESCRIP,ENDOSO_AGRUP,NOMBRE_CONVENIO,FLOTA_CONVENIO,SUCURSAL,COD_SUCURSAL1,SUMA_ASEG_RC,ORIGEN,ASEGURADO_RUT,ANO_REF_INI,NUM_ITEMS_CONTRA,FLOTA_CONTRA,COD_CONVENIO,FLOTA,COD_SUCURSAL,LC_MODEL,LC_MODEL_DEF,MES_REF_INI,PRIMA_RECIBO,PRIMA_RECIBO_FINAL,COB_INI,COB_FIN,FECHA_COTRENOV,PLAN_DESC,TIPO_PLAN,ANTERIOR,NUM_ITEMS,COD_MARCA_P,COD_MODELO_P,COD_TIPO_P,CANAL,DURACION_PLAN,ORIGEN_MARCA,ANTIG_VEHICULO,PT_RO,DATE_UPDATE,FORMA_PAGO_INI,FORMA_PAGO_FIN,METODO_PAGO,RAZON_CUOTAS,TUVO_PT,FORMA_PAGO_DEF,TIPO_PERS,SEXO,NACIONALIDAD,SEXO_ASEGURADO,FECHA_NACIMIENTO,EDAD_ASEGURADO,KEY
0,481133,00054010,1852,6006870,100,2010-01-22,2010-10-23,2010-10-23,274,274,23,408,L,23408013,TUCSON 2.0 GL 2WD S/AC (BASE),PARTICULAR,2007,WE4534,5,JEEP,HYUNDAI,TUCSON,G4GC6670735,81554700,MARSH,468,Worksite Aguas Andinas,40,PLAN INTEGRAL,0.0,0.0,7953654,RIVERA SUAREZ MIRNA VERONICA,0,NaN,10.25,10.25,0.0,0.1,10.25,803,SE DEJA CONSTANCIA QUE SE ELIMINA CLAUSULA DE DEDUCIBLE POR INSPECCION: SE OBTIENE COBERTURA A...,AJUSTE,WS AGUAS ANDINAS,0,HENDAYA,00000010,800.0000000000,LIBERTY,8284647,2010,1,0,1852,0,10,NaN,NaN,201001,10.243978,10.243978,10383,10383,2010-01-22,RC + DM + RO,FULL,NO,22,NaN,NaN,NaN,TRADICIONAL,MENOS 1 ANO,COREA DEL SUR,3,0,2022-06-14,AVISO CUOTA,AVISO CUOTA,AVISO CUOTA,NaN,NaN,AVISO CUOTA,PNat,1,C,F,1958-03-05,52,6006870-100-LIBERTY
1,494715,00054010,1852,6006870,101,2010-01-30,2010-10-23,2010-10-23,266,266,77,415,L,77415003,GRAND CARNIVAL DSL MEC AC,PARTICULAR,2010,NaN,2,STATION WAGON,KIA MOTORS,GRAN CARNIVAL,G6EA9A425706,81554700,MARSH,468,Worksite Aguas Andinas,40,PLAN INTEGRAL,0.0,0.0,9292753,FUENZALIDA ADROVER ROBERTO ALEJANDRO,0,NaN,11.27,11.27,0.0,0.1,11.27,100,NaN,NUEVA PROD,WS AGUAS ANDINAS,0,HENDAYA,00000010,800.0000000000,LIBERTY,9292753,2010,2,0,1852,0,10,NaN,NaN,201001,11.279323,11.279323,10383,10383,2010-02-01,RC + DM + RO,FULL,NO,22,NaN,NaN,NaN,TRADICIONAL,MENOS 1 ANO,COREA DEL SUR,0,0,2022-06-14,PAC,PAC,PAC,NaN,NaN,PAC,PNat,1,C,F,1962-06-01,48,6006870-101-LIBERTY
2,522349,00054010,1852,6006870,102,2010-02-05,2010-10-23,2010-10-23,260,260,25,218,L,25218001,CR-V EX 2.4 AUT. 4X4,PARTICULAR,2010,CFZH38,5,JEEP,HONDA,CRV,K24Z15611327,81554700,MARSH,468,Worksite Aguas Andinas,40,PLAN INTEGRAL,0.0,0.0,8041326,BASCUR FAUNDEZ MARITZA SOLEDAD,0,NaN,10.25,10.25,0.0,0.1,10.25,803,"MEDIANTE EL PRESENTE ENDOSO, SE DEJA CONSTANCIA QUE SE MODIFICA LO SIGUIENTE: PATENTE : CFZH-3...",AJUSTE,WS AGUAS ANDINAS,0,HENDAYA,00000010,800.0000000000,LIBERTY,8041326,2010,4,0,1852,0,10,NaN,NaN,201002,10.234038,10.234038,10383,10383,2010-02-05,RC + DM + RO,FULL,NO,22,NaN,NaN,NaN,TRADICIONAL,MENOS 1 ANO,JAPON,0,0,2022-06-14,PAT,PAT,PAT,Redocumentación,NaN,PAT,PNat,0,C,M,1960-03-08,50,6006870-102-LIBERTY
3,543518,00054010,1852,6006870,103,2010-02-23,2010-10-23,2010-10-23,242,242,61,104,L,61104008,"SWIFT 1,3 GL",PARTICULAR,2008,BHKK88,1,AUTOMOVIL,SUZUKI,SWIFT,M13A-2002565,81554700,MARSH,468,Worksite Aguas Andinas,40,PLAN INTEGRAL,0.0,0.0,14186796,CASTILLO ARTIGAS PAMELA ANDREA,0,NaN,10.25,10.25,0.0,0.1,10.25,100,NaN,NUEVA PROD,WS AGUAS ANDINAS,0,HENDAYA,00000010,800.0000000000,LIBERTY,14186796,2010,1,0,1852,0,10,NaN,NaN,201002,10.241115,10.241115,10383,10383,2010-02-23,RC + DM + RO,FULL,NO,22,NaN,NaN,NaN,TRADICIONAL,MENOS 1 ANO,JAPON,2,0,2022-06-14,PAC,PAC,PAC,NaN,NaN,PAC,PNat,1,NaN,F,1981-09-14,28,6006870-103-LIBERTY
4,555526,00054010,1852,6006870,104,2010-03-10,2010-10-23,2010-10-23,227,227,61,161,L,61161023,AERIO SEDAN GLX A ABS,PARTICULAR,2006,WR4929,1,AUTOMOVIL,SUZUKI,AERIO,M16A-1172573,81554700,MARSH,468,Worksite Aguas Andinas,40,PLAN INTEGRAL,0.0,0.0,10766702,PERALTA RODRÍGUEZ IRIS GIOVANA,0,NaN,10.25,10.25,0.0,0.1,10.25,803,SE DEJA CONSTANCIA QUE SE ELIMINA CLAUSULA DE DEDUCIBLE POR INSPECCION: SE OBTIENE COBERTURA A...,AJUSTE,WS AGUAS ANDINAS,0,HENDAYA,00000010,800.0000000000,LIBERTY,10766702,2010,2,0,1852,0,10,NaN,NaN,201003,10.242511,10.242511,10383,10383,2010-03-10,RC + DM + RO,FULL,NO,22,NaN,NaN,NaN,TRADICIONAL,MENOS 1 ANO,JAPON,4,0,2022-06-14,PAC,PAC,PAC,NaN,NaN,PAC,PNat,1,NaN,F,1967-07-01,43,6006870-104-LIBERTY

In [13]:
#Ajuste de datos para comparar

dfp['FLOTA1']=corregirColumna(dfp,'FLOTA1')
dfs['FECHA_COTRENOV'] = pd.to_datetime(dfs['FECHA_COTRENOV'],format="%Y-%m-%d %H:%M:%S", errors = 'coerce').dt.strftime('%Y-%m-%d')

In [14]:
dfp.columns = dfp.columns.str.upper()
#dfp = dfp[['KEY','SSEGURO','LC_MODEL','LC_MODEL_DEF','MES_REF_INI','PRIMA_RECIBO','PRIMA_RECIBO_FINAL','COB_INI','COB_FIN','FECHA_COTRENOV','PLAN_DESC','TIPO_PLAN','ANTERIOR','NUM_ITEMS','COD_MARCA_P','COD_MODELO_P','COD_TIPO_P','CANAL','DURACION_PLAN','ORIGEN_MARCA','ANTIG_VEHICULO','PT_RO','DATE_UPDATE','FORMA_PAGO_INI','FORMA_PAGO_FIN','METODO_PAGO','RAZON_CUOTAS','TUVO_PT','FORMA_PAGO_DEF']]

In [15]:
dfp.isna().sum()

SSEGURO                  0
CAGENTE                  0
CAGRSEG             239209
POLIZA                   0
ITEM                     0
                     ...
NACIONALIDAD        336839
SEXO_ASEGURADO      188373
FECHA_NACIMIENTO    110834
EDAD_ASEGURADO      110836
KEY                      0
Length: 90, dtype: int64

In [16]:
dfp[dfp.duplicated(['KEY'])]

Empty DataFrame
Columns: [SSEGURO, CAGENTE, CAGRSEG, POLIZA, ITEM, INI_VIG, FIN_VIG_ORIG, FIN_VIG_ACT, DIAS_VIGENTE, DIAS_SUSCRITOS, VEH_CMARCA, VEH_CMODELO, VEH_CLASE, VEH_CVERSION, TVERSION, USO, VEH_ANO, PATENTE, VEH_CTIPO, VEH_TIPO, TMARCA, TMODELO, NUM_MOTOR, CORREDOR_RUT, CORREDOR, COD_PRODUCTO, PRODUCTO, COD_PLAN, PLAN, DEDUCIBLE, DEDUCIBLE_INI, CONTRATANTE_RUT, CONTRATANTE_NOMBRE, FLOTA1, NRO_MASIVO, PRIMA, PRIMA_TARIFA, DESCUENTO, COMISION, PRIMA_FINAL, COD_ENDOSO, TDESCRIP, ENDOSO_AGRUP, NOMBRE_CONVENIO, FLOTA_CONVENIO, SUCURSAL, COD_SUCURSAL1, SUMA_ASEG_RC, ORIGEN, ASEGURADO_RUT, ANO_REF_INI, NUM_ITEMS_CONTRA, FLOTA_CONTRA, COD_CONVENIO, FLOTA, COD_SUCURSAL, LC_MODEL, LC_MODEL_DEF, MES_REF_INI, PRIMA_RECIBO, PRIMA_RECIBO_FINAL, COB_INI, COB_FIN, FECHA_COTRENOV, PLAN_DESC, TIPO_PLAN, ANTERIOR, NUM_ITEMS, COD_MARCA_P, COD_MODELO_P, COD_TIPO_P, CANAL, DURACION_PLAN, ORIGEN_MARCA, ANTIG_VEHICULO, PT_RO, DATE_UPDATE, FORMA_PAGO_INI, FORMA_PAGO_FIN, METODO_PAGO, RAZON_CUOTAS, TUVO_PT, FORMA_PAGO_DEF, TIPO_PERS, SEXO, NACIONALIDAD, SEXO_ASEGURADO, FECHA_NACIMIENTO, EDAD_ASEGURADO, KEY]
Index: []

In [17]:
dfp[dfp.duplicated()].sort_values('KEY')

Empty DataFrame
Columns: [SSEGURO, CAGENTE, CAGRSEG, POLIZA, ITEM, INI_VIG, FIN_VIG_ORIG, FIN_VIG_ACT, DIAS_VIGENTE, DIAS_SUSCRITOS, VEH_CMARCA, VEH_CMODELO, VEH_CLASE, VEH_CVERSION, TVERSION, USO, VEH_ANO, PATENTE, VEH_CTIPO, VEH_TIPO, TMARCA, TMODELO, NUM_MOTOR, CORREDOR_RUT, CORREDOR, COD_PRODUCTO, PRODUCTO, COD_PLAN, PLAN, DEDUCIBLE, DEDUCIBLE_INI, CONTRATANTE_RUT, CONTRATANTE_NOMBRE, FLOTA1, NRO_MASIVO, PRIMA, PRIMA_TARIFA, DESCUENTO, COMISION, PRIMA_FINAL, COD_ENDOSO, TDESCRIP, ENDOSO_AGRUP, NOMBRE_CONVENIO, FLOTA_CONVENIO, SUCURSAL, COD_SUCURSAL1, SUMA_ASEG_RC, ORIGEN, ASEGURADO_RUT, ANO_REF_INI, NUM_ITEMS_CONTRA, FLOTA_CONTRA, COD_CONVENIO, FLOTA, COD_SUCURSAL, LC_MODEL, LC_MODEL_DEF, MES_REF_INI, PRIMA_RECIBO, PRIMA_RECIBO_FINAL, COB_INI, COB_FIN, FECHA_COTRENOV, PLAN_DESC, TIPO_PLAN, ANTERIOR, NUM_ITEMS, COD_MARCA_P, COD_MODELO_P, COD_TIPO_P, CANAL, DURACION_PLAN, ORIGEN_MARCA, ANTIG_VEHICULO, PT_RO, DATE_UPDATE, FORMA_PAGO_INI, FORMA_PAGO_FIN, METODO_PAGO, RAZON_CUOTAS, TUVO_PT, FORMA_PAGO_DEF, TIPO_PERS, SEXO, NACIONALIDAD, SEXO_ASEGURADO, FECHA_NACIMIENTO, EDAD_ASEGURADO, KEY]
Index: []

In [18]:
dfp['KEY']= dfp['KEY'].astype(str)
dfs['KEY']= dfs['KEY'].astype(str)
df2 = pd.merge(dfs['KEY'], dfp['KEY'], how='outer',
      left_on=['KEY'],
      right_on=['KEY'],
      left_index=False,
      right_index=False, 
      sort=True,
     suffixes=('_x', '_y'), copy=True, indicator=True,
     validate=None)
df2

                       KEY     _merge
0       10361804-265-PENTA  left_only
1       10392980-713-PENTA  left_only
2       10392980-716-PENTA  left_only
3       10392980-747-PENTA  left_only
4       10392980-750-PENTA  left_only
...                    ...        ...
932784   6999743-1-LIBERTY  left_only
932785   6999748-1-LIBERTY  left_only
932786   6999888-1-LIBERTY  left_only
932787   6999890-1-LIBERTY  left_only
932788   6999892-1-LIBERTY  left_only

[932789 rows x 2 columns]

In [19]:
df2.groupby(['_merge']).size()

_merge
left_only     432789
right_only    432789
both           67211
dtype: int64

In [20]:
dfp = dfp[dfp['KEY'].isin(dfs['KEY'])].dropna(how = 'all')
dfs = dfs[dfs['KEY'].isin(dfp['KEY'])].dropna(how = 'all')
dfp.shape

(67211, 90)

In [24]:
### SSEGURO

dfp1 = dfp[['KEY', 'SSEGURO']]
dfs1 = dfs[['KEY', 'SSEGURO']]

dfp1['SSEGURO'] = dfp1['SSEGURO'].astype(str).copy()
dfs1['SSEGURO'] = dfs1['SSEGURO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.SSEGURO_p != dfm.SSEGURO_s) & (~dfm.SSEGURO_s.isnull()) & (~dfm.SSEGURO_p.isnull())].copy()
dfm1[['KEY','SSEGURO_p','SSEGURO_s']]

<ipython-input-24-46dfc34951e2>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['SSEGURO'] = dfp1['SSEGURO'].astype(str).copy()
<ipython-input-24-46dfc34951e2>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['SSEGURO'] = dfs1['SSEGURO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO_p, SSEGURO_s]
Index: []

In [25]:
### CAGENTE

dfp1 = dfp[['KEY', 'SSEGURO', 'CAGENTE']]
dfs1 = dfs[['KEY', 'CAGENTE']]

dfp1['CAGENTE'] = dfp1['CAGENTE'].astype(str).copy()
dfs1['CAGENTE'] = dfs1['CAGENTE'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.CAGENTE_p != dfm.CAGENTE_s) & (~dfm.CAGENTE_s.isnull()) & (~dfm.CAGENTE_p.isnull())].copy()
dfm1[['KEY','SSEGURO','CAGENTE_p','CAGENTE_s']]

<ipython-input-25-809a89dd655a>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['CAGENTE'] = dfp1['CAGENTE'].astype(str).copy()
<ipython-input-25-809a89dd655a>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['CAGENTE'] = dfs1['CAGENTE'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, CAGENTE_p, CAGENTE_s]
Index: []

In [26]:
### CAGRSEG

dfp1 = dfp[['KEY', 'SSEGURO', 'CAGRSEG']]
dfs1 = dfs[['KEY', 'CAGRSEG']]

dfp1['CAGRSEG'] = dfp1['CAGRSEG'].astype(str).copy()
dfs1['CAGRSEG'] = dfs1['CAGRSEG'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.CAGRSEG_p != dfm.CAGRSEG_s) & (~dfm.CAGRSEG_s.isnull()) & (~dfm.CAGRSEG_p.isnull())].copy()
dfm1[['KEY','SSEGURO','CAGRSEG_p','CAGRSEG_s']]

<ipython-input-26-8c159844712e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['CAGRSEG'] = dfp1['CAGRSEG'].astype(str).copy()
<ipython-input-26-8c159844712e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['CAGRSEG'] = dfs1['CAGRSEG'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, CAGRSEG_p, CAGRSEG_s]
Index: []

In [27]:
### POLIZA

dfp1 = dfp[['KEY', 'SSEGURO', 'POLIZA']]
dfs1 = dfs[['KEY', 'POLIZA']]

dfp1['POLIZA'] = dfp1['POLIZA'].astype(str).copy()
dfs1['POLIZA'] = dfs1['POLIZA'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.POLIZA_p != dfm.POLIZA_s) & (~dfm.POLIZA_s.isnull()) & (~dfm.POLIZA_p.isnull())].copy()
dfm1[['KEY','SSEGURO','POLIZA_p','POLIZA_s']]

<ipython-input-27-11a411c8fd25>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['POLIZA'] = dfp1['POLIZA'].astype(str).copy()
<ipython-input-27-11a411c8fd25>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['POLIZA'] = dfs1['POLIZA'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, POLIZA_p, POLIZA_s]
Index: []

In [28]:
### ITEM

dfp1 = dfp[['KEY', 'SSEGURO', 'ITEM']]
dfs1 = dfs[['KEY', 'ITEM']]

dfp1['ITEM'] = dfp1['ITEM'].astype(str).copy()
dfs1['ITEM'] = dfs1['ITEM'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.ITEM_p != dfm.ITEM_s) & (~dfm.ITEM_s.isnull()) & (~dfm.ITEM_p.isnull())].copy()
dfm1[['KEY','SSEGURO','ITEM_p','ITEM_s']]

<ipython-input-28-5bbd65a4a562>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['ITEM'] = dfp1['ITEM'].astype(str).copy()
<ipython-input-28-5bbd65a4a562>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['ITEM'] = dfs1['ITEM'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, ITEM_p, ITEM_s]
Index: []

In [29]:
### INI_VIG

dfp1 = dfp[['KEY', 'SSEGURO', 'INI_VIG']]
dfs1 = dfs[['KEY', 'INI_VIG']]

dfp1['INI_VIG'] = dfp1['INI_VIG'].astype(str).copy()
dfs1['INI_VIG'] = dfs1['INI_VIG'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.INI_VIG_p != dfm.INI_VIG_s) & (~dfm.INI_VIG_s.isnull()) & (~dfm.INI_VIG_p.isnull())].copy()
dfm1[['KEY','SSEGURO','INI_VIG_p','INI_VIG_s']]

<ipython-input-29-5a22819c5b66>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['INI_VIG'] = dfp1['INI_VIG'].astype(str).copy()
<ipython-input-29-5a22819c5b66>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['INI_VIG'] = dfs1['INI_VIG'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, INI_VIG_p, INI_VIG_s]
Index: []

In [30]:
### FIN_VIG_ORIG

dfp1 = dfp[['KEY', 'SSEGURO', 'FIN_VIG_ORIG']]
dfs1 = dfs[['KEY', 'FIN_VIG_ORIG']]

dfp1['FIN_VIG_ORIG'] = dfp1['FIN_VIG_ORIG'].astype(str).copy()
dfs1['FIN_VIG_ORIG'] = dfs1['FIN_VIG_ORIG'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FIN_VIG_ORIG_p != dfm.FIN_VIG_ORIG_s) & (~dfm.FIN_VIG_ORIG_s.isnull()) & (~dfm.FIN_VIG_ORIG_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FIN_VIG_ORIG_p','FIN_VIG_ORIG_s']]

<ipython-input-30-72f930830807>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FIN_VIG_ORIG'] = dfp1['FIN_VIG_ORIG'].astype(str).copy()
<ipython-input-30-72f930830807>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FIN_VIG_ORIG'] = dfs1['FIN_VIG_ORIG'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, FIN_VIG_ORIG_p, FIN_VIG_ORIG_s]
Index: []

In [31]:
### FIN_VIG_ACT

dfp1 = dfp[['KEY', 'SSEGURO', 'FIN_VIG_ACT']]
dfs1 = dfs[['KEY', 'FIN_VIG_ACT']]

dfp1['FIN_VIG_ACT'] = dfp1['FIN_VIG_ACT'].astype(str).copy()
dfs1['FIN_VIG_ACT'] = dfs1['FIN_VIG_ACT'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FIN_VIG_ACT_p != dfm.FIN_VIG_ACT_s) & (~dfm.FIN_VIG_ACT_s.isnull()) & (~dfm.FIN_VIG_ACT_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FIN_VIG_ACT_p','FIN_VIG_ACT_s']]

<ipython-input-31-ac545ddd6b98>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FIN_VIG_ACT'] = dfp1['FIN_VIG_ACT'].astype(str).copy()
<ipython-input-31-ac545ddd6b98>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FIN_VIG_ACT'] = dfs1['FIN_VIG_ACT'].astype(str).copy()

                      KEY    SSEGURO FIN_VIG_ACT_p FIN_VIG_ACT_s
63462  61388119-1-LIBERTY  906118132    2022-06-06    2022-06-18
66679  61416374-1-LIBERTY  906358167    2022-08-31    2022-05-24

In [32]:
### DIAS_VIGENTE

dfp1 = dfp[['KEY', 'SSEGURO', 'DIAS_VIGENTE']]
dfs1 = dfs[['KEY', 'DIAS_VIGENTE']]

dfp1['DIAS_VIGENTE'] = dfp1['DIAS_VIGENTE'].astype(str).copy()
dfs1['DIAS_VIGENTE'] = dfs1['DIAS_VIGENTE'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.DIAS_VIGENTE_p != dfm.DIAS_VIGENTE_s) & (~dfm.DIAS_VIGENTE_s.isnull()) & (~dfm.DIAS_VIGENTE_p.isnull())].copy()
dfm1[['KEY','SSEGURO','DIAS_VIGENTE_p','DIAS_VIGENTE_s']]

<ipython-input-32-d9dbf0fff63a>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['DIAS_VIGENTE'] = dfp1['DIAS_VIGENTE'].astype(str).copy()
<ipython-input-32-d9dbf0fff63a>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['DIAS_VIGENTE'] = dfs1['DIAS_VIGENTE'].astype(str).copy()

                      KEY    SSEGURO DIAS_VIGENTE_p DIAS_VIGENTE_s
63462  61388119-1-LIBERTY  906118132            353            365
66679  61416374-1-LIBERTY  906358167            365            266

In [33]:
### DIAS_SUSCRITOS

dfp1 = dfp[['KEY', 'SSEGURO', 'DIAS_SUSCRITOS']]
dfs1 = dfs[['KEY', 'DIAS_SUSCRITOS']]

dfp1['DIAS_SUSCRITOS'] = dfp1['DIAS_SUSCRITOS'].astype(str).copy()
dfs1['DIAS_SUSCRITOS'] = dfs1['DIAS_SUSCRITOS'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.DIAS_SUSCRITOS_p != dfm.DIAS_SUSCRITOS_s) & (~dfm.DIAS_SUSCRITOS_s.isnull()) & (~dfm.DIAS_SUSCRITOS_p.isnull())].copy()
dfm1[['KEY','SSEGURO','DIAS_SUSCRITOS_p','DIAS_SUSCRITOS_s']]

<ipython-input-33-c0efacf7bf5e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['DIAS_SUSCRITOS'] = dfp1['DIAS_SUSCRITOS'].astype(str).copy()
<ipython-input-33-c0efacf7bf5e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['DIAS_SUSCRITOS'] = dfs1['DIAS_SUSCRITOS'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, DIAS_SUSCRITOS_p, DIAS_SUSCRITOS_s]
Index: []

In [34]:
### VEH_CMARCA

dfp1 = dfp[['KEY', 'SSEGURO', 'VEH_CMARCA']]
dfs1 = dfs[['KEY', 'VEH_CMARCA']]

dfp1['VEH_CMARCA'] = dfp1['VEH_CMARCA'].astype(str).copy()
dfs1['VEH_CMARCA'] = dfs1['VEH_CMARCA'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.VEH_CMARCA_p != dfm.VEH_CMARCA_s) & (~dfm.VEH_CMARCA_s.isnull()) & (~dfm.VEH_CMARCA_p.isnull())].copy()
dfm1[['KEY','SSEGURO','VEH_CMARCA_p','VEH_CMARCA_s']]

<ipython-input-34-a9328fb4c082>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['VEH_CMARCA'] = dfp1['VEH_CMARCA'].astype(str).copy()
<ipython-input-34-a9328fb4c082>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['VEH_CMARCA'] = dfs1['VEH_CMARCA'].astype(str).copy()

                      KEY    SSEGURO VEH_CMARCA_p VEH_CMARCA_s
11465  61008920-2-LIBERTY  900006999         1262          1E3
13118  61022534-2-LIBERTY  900147490         1110          1E3
13485  61025777-1-LIBERTY  900361211         1100          1E3
13720  61028040-1-LIBERTY  900311198         1053          1E3
14162  61033412-1-LIBERTY  900424087         1053          1E3
...                   ...        ...          ...          ...
64863  61400787-4-LIBERTY  906290300         1087          1E3
64864  61400787-5-LIBERTY  906290301         1087          1E3
64971  61401540-1-LIBERTY  906277270         1053          1E3
65316  61404327-1-LIBERTY  906312734         1368          1E3
66563  61415684-1-LIBERTY  906274972         1100          1E3

[90 rows x 4 columns]

In [35]:
### VEH_CMODELO

dfp1 = dfp[['KEY', 'SSEGURO', 'VEH_CMODELO']]
dfs1 = dfs[['KEY', 'VEH_CMODELO']]

dfp1['VEH_CMODELO'] = dfp1['VEH_CMODELO'].astype(str).copy()
dfs1['VEH_CMODELO'] = dfs1['VEH_CMODELO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.VEH_CMODELO_p != dfm.VEH_CMODELO_s) & (~dfm.VEH_CMODELO_s.isnull()) & (~dfm.VEH_CMODELO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','VEH_CMODELO_p','VEH_CMODELO_s']]

<ipython-input-35-ca0624451e53>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['VEH_CMODELO'] = dfp1['VEH_CMODELO'].astype(str).copy()
<ipython-input-35-ca0624451e53>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['VEH_CMODELO'] = dfs1['VEH_CMODELO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, VEH_CMODELO_p, VEH_CMODELO_s]
Index: []

In [36]:
### VEH_CLASE

dfp1 = dfp[['KEY', 'SSEGURO', 'VEH_CLASE']]
dfs1 = dfs[['KEY', 'VEH_CLASE']]

dfp1['VEH_CLASE'] = dfp1['VEH_CLASE'].astype(str).copy()
dfs1['VEH_CLASE'] = dfs1['VEH_CLASE'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.VEH_CLASE_p != dfm.VEH_CLASE_s) & (~dfm.VEH_CLASE_s.isnull()) & (~dfm.VEH_CLASE_p.isnull())].copy()
dfm1[['KEY','SSEGURO','VEH_CLASE_p','VEH_CLASE_s']]

<ipython-input-36-5a2b38cc7790>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['VEH_CLASE'] = dfp1['VEH_CLASE'].astype(str).copy()
<ipython-input-36-5a2b38cc7790>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['VEH_CLASE'] = dfs1['VEH_CLASE'].astype(str).copy()

                      KEY    SSEGURO VEH_CLASE_p VEH_CLASE_s
236     6057038-2-LIBERTY     626179           L           P
1896    6065574-1-LIBERTY     402453           L           P
3169    6074411-1-LIBERTY     523172           L           P
3307    6075132-1-LIBERTY     529756           L           P
4598    6080619-1-LIBERTY     574688           L           P
...                   ...        ...         ...         ...
61740  61372794-1-LIBERTY  905874216           L           P
63534   6138883-1-LIBERTY    1084035           L           P
65746   6140894-1-LIBERTY    1180289           L           P
66312  61413657-1-LIBERTY  906357007           L           P
66498   6141509-1-LIBERTY    1186329           L           P

[89 rows x 4 columns]

In [37]:
### VEH_CVERSION

dfp1 = dfp[['KEY', 'SSEGURO', 'VEH_CVERSION']]
dfs1 = dfs[['KEY', 'VEH_CVERSION']]

dfp1['VEH_CVERSION'] = dfp1['VEH_CVERSION'].astype(str).copy()
dfs1['VEH_CVERSION'] = dfs1['VEH_CVERSION'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.VEH_CVERSION_p != dfm.VEH_CVERSION_s) & (~dfm.VEH_CVERSION_s.isnull()) & (~dfm.VEH_CVERSION_p.isnull())].copy()
dfm1[['KEY','SSEGURO','VEH_CVERSION_p','VEH_CVERSION_s']]

<ipython-input-37-3b53b86e76b8>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['VEH_CVERSION'] = dfp1['VEH_CVERSION'].astype(str).copy()
<ipython-input-37-3b53b86e76b8>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['VEH_CVERSION'] = dfs1['VEH_CVERSION'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, VEH_CVERSION_p, VEH_CVERSION_s]
Index: []

In [38]:
### TVERSION

dfp1 = dfp[['KEY', 'SSEGURO', 'TVERSION']]
dfs1 = dfs[['KEY', 'TVERSION']]

dfp1['TVERSION'] = dfp1['TVERSION'].astype(str).copy()
dfs1['TVERSION'] = dfs1['TVERSION'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.TVERSION_p != dfm.TVERSION_s) & (~dfm.TVERSION_s.isnull()) & (~dfm.TVERSION_p.isnull())].copy()
dfm1[['KEY','SSEGURO','TVERSION_p','TVERSION_s']]

<ipython-input-38-eb83ecf50861>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['TVERSION'] = dfp1['TVERSION'].astype(str).copy()
<ipython-input-38-eb83ecf50861>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['TVERSION'] = dfs1['TVERSION'].astype(str).copy()

,KEY,SSEGURO,TVERSION_p,TVERSION_s
3528,6076134-1-LIBERTY,540477,9200i TRACTO CAMIÓN,9200i TRACTO CAMION
3615,6076522-1-LIBERTY,543654,"K-100 CAMION O TRACTO CAMION 6X4, 5ª RUE","K-100 CAMION O TRACTO CAMION 6X4, 5? RUE"
3616,6076522-3-LIBERTY,1090601,"K-100 CAMION O TRACTO CAMION 6X4, 5ª RUE","K-100 CAMION O TRACTO CAMION 6X4, 5? RUE"
4768,6081372-4-LIBERTY,581588,FC-114 Y FC-124 6 TON 7 TON.,FC-114 Y FC-124 6 TON; 7 TON.
5101,6082954-1-LIBERTY,591741,"K-100 CAMION O TRACTO CAMION 6X4, 5ª RUE","K-100 CAMION O TRACTO CAMION 6X4, 5? RUE"
...,...,...,...,...
61480,61370276-1-LIBERTY,905777819,"CANTER 3,5 Ó 4 TON.","CANTER 3,5 O 4 TON."
63151,61385693-1-LIBERTY,906022193,LAND CRUISER 4.1,LAND CRUISER 4.1
63552,61389026-1-LIBERTY,906136461,SIGNATURE LIMITED 4.6 AUT,SIGNATURE LIMITED 4.6 AUT
63563,61389178-1-LIBERTY,906120053,440I COUPÉ SPORT 3.0 AT,440I COUPE SPORT 3.0 AT
65872,61409772-1-LIBERTY,906274196,"CANTER 3,5 Ó 4 TON.","CANTER 3,5 O 4 TON."

In [39]:
### USO

dfp1 = dfp[['KEY', 'SSEGURO', 'USO']]
dfs1 = dfs[['KEY', 'USO']]

dfp1['USO'] = dfp1['USO'].astype(str).copy()
dfs1['USO'] = dfs1['USO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.USO_p != dfm.USO_s) & (~dfm.USO_s.isnull()) & (~dfm.USO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','USO_p','USO_s']]

<ipython-input-39-9f0bce047997>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['USO'] = dfp1['USO'].astype(str).copy()
<ipython-input-39-9f0bce047997>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['USO'] = dfs1['USO'].astype(str).copy()

                      KEY    SSEGURO        USO_p       USO_s
3760    6077131-1-LIBERTY     549443  DESCONOCIDO  DESCONOCID
4533    6080356-1-LIBERTY     572219  DESCONOCIDO  DESCONOCID
6878    6087090-1-LIBERTY     626714  DESCONOCIDO  DESCONOCID
7140    6088370-1-LIBERTY     638510  DESCONOCIDO  DESCONOCID
7141   6088370-11-LIBERTY     638825  DESCONOCIDO  DESCONOCID
...                   ...        ...          ...         ...
65285  61404035-1-LIBERTY  906311463  DESCONOCIDO  DESCONOCID
65460   6140560-1-LIBERTY    1175290  DESCONOCIDO  DESCONOCID
65469   6140567-1-LIBERTY    1175548  DESCONOCIDO  DESCONOCID
65761  61409085-1-LIBERTY  906326424  DESCONOCIDO  DESCONOCID
67147  61420931-1-LIBERTY  906437457  DESCONOCIDO  DESCONOCID

[92 rows x 4 columns]

In [40]:
### VEH_ANO

dfp1 = dfp[['KEY', 'SSEGURO', 'VEH_ANO']]
dfs1 = dfs[['KEY', 'VEH_ANO']]

dfp1['VEH_ANO'] = dfp1['VEH_ANO'].astype(str).copy()
dfs1['VEH_ANO'] = dfs1['VEH_ANO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.VEH_ANO_p != dfm.VEH_ANO_s) & (~dfm.VEH_ANO_s.isnull()) & (~dfm.VEH_ANO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','VEH_ANO_p','VEH_ANO_s']]

<ipython-input-40-f5fe6dc8a5c1>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['VEH_ANO'] = dfp1['VEH_ANO'].astype(str).copy()
<ipython-input-40-f5fe6dc8a5c1>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['VEH_ANO'] = dfs1['VEH_ANO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, VEH_ANO_p, VEH_ANO_s]
Index: []

In [41]:
### PATENTE

dfp1 = dfp[['KEY', 'SSEGURO', 'PATENTE']]
dfs1 = dfs[['KEY', 'PATENTE']]

dfp1['PATENTE'] = dfp1['PATENTE'].astype(str).copy()
dfs1['PATENTE'] = dfs1['PATENTE'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.PATENTE_p != dfm.PATENTE_s) & (~dfm.PATENTE_s.isnull()) & (~dfm.PATENTE_p.isnull())].copy()
dfm1[['KEY','SSEGURO','PATENTE_p','PATENTE_s']]

<ipython-input-41-70d790c0bae9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['PATENTE'] = dfp1['PATENTE'].astype(str).copy()
<ipython-input-41-70d790c0bae9>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['PATENTE'] = dfs1['PATENTE'].astype(str).copy()

                      KEY    SSEGURO PATENTE_p PATENTE_s
64594  61399106-1-LIBERTY  906017298  "LKHZ74"  LKHZ74\r
64687  61399366-1-LIBERTY  906118346    LHZH27       nan

In [42]:
### VEH_CTIPO

dfp1 = dfp[['KEY', 'SSEGURO', 'VEH_CTIPO']]
dfs1 = dfs[['KEY', 'VEH_CTIPO']]

dfp1['VEH_CTIPO'] = dfp1['VEH_CTIPO'].astype(str).copy()
dfs1['VEH_CTIPO'] = dfs1['VEH_CTIPO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.VEH_CTIPO_p != dfm.VEH_CTIPO_s) & (~dfm.VEH_CTIPO_s.isnull()) & (~dfm.VEH_CTIPO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','VEH_CTIPO_p','VEH_CTIPO_s']]

<ipython-input-42-6a43ff0ace53>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['VEH_CTIPO'] = dfp1['VEH_CTIPO'].astype(str).copy()
<ipython-input-42-6a43ff0ace53>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['VEH_CTIPO'] = dfs1['VEH_CTIPO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, VEH_CTIPO_p, VEH_CTIPO_s]
Index: []

In [43]:
### VEH_TIPO

dfp1 = dfp[['KEY', 'SSEGURO', 'VEH_TIPO']]
dfs1 = dfs[['KEY', 'VEH_TIPO']]

dfp1['VEH_TIPO'] = dfp1['VEH_TIPO'].astype(str).copy()
dfs1['VEH_TIPO'] = dfs1['VEH_TIPO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.VEH_TIPO_p != dfm.VEH_TIPO_s) & (~dfm.VEH_TIPO_s.isnull()) & (~dfm.VEH_TIPO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','VEH_TIPO_p','VEH_TIPO_s']]

<ipython-input-43-4d3ba1c83583>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['VEH_TIPO'] = dfp1['VEH_TIPO'].astype(str).copy()
<ipython-input-43-4d3ba1c83583>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['VEH_TIPO'] = dfs1['VEH_TIPO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, VEH_TIPO_p, VEH_TIPO_s]
Index: []

In [44]:
### TMARCA

dfp1 = dfp[['KEY', 'SSEGURO', 'TMARCA']]
dfs1 = dfs[['KEY', 'TMARCA']]

dfp1['TMARCA'] = dfp1['TMARCA'].astype(str).copy()
dfs1['TMARCA'] = dfs1['TMARCA'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.TMARCA_p != dfm.TMARCA_s) & (~dfm.TMARCA_s.isnull()) & (~dfm.TMARCA_p.isnull())].copy()
dfm1[['KEY','SSEGURO','TMARCA_p','TMARCA_s']]

<ipython-input-44-d465f7523d68>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['TMARCA'] = dfp1['TMARCA'].astype(str).copy()
<ipython-input-44-d465f7523d68>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['TMARCA'] = dfs1['TMARCA'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, TMARCA_p, TMARCA_s]
Index: []

In [45]:
### TMODELO

dfp1 = dfp[['KEY', 'SSEGURO', 'TMODELO']]
dfs1 = dfs[['KEY', 'TMODELO']]

dfp1['TMODELO'] = dfp1['TMODELO'].astype(str).copy()
dfs1['TMODELO'] = dfs1['TMODELO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.TMODELO_p != dfm.TMODELO_s) & (~dfm.TMODELO_s.isnull()) & (~dfm.TMODELO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','TMODELO_p','TMODELO_s']]

<ipython-input-45-31d61ddb03d6>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['TMODELO'] = dfp1['TMODELO'].astype(str).copy()
<ipython-input-45-31d61ddb03d6>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['TMODELO'] = dfs1['TMODELO'].astype(str).copy()

,KEY,SSEGURO,TMODELO_p,TMODELO_s
2237,6069768-1-LIBERTY,457065,CARGO 1622 ó 1722,CARGO 1622 o 1722
2633,6071834-1-LIBERTY,480557,FLB ó FLD,FLB o FLD
2726,6072369-1-LIBERTY,484402,CARGO 1416 ó 1516,CARGO 1416 o 1516
2863,6072972-1-LIBERTY,489133,"CL, CLT, LN ó LNT 9000","CL, CLT, LN o LNT 9000"
3402,6075601-1-LIBERTY,535859,FC144 ó FC3JJ ó FC4J,FC144 o FC3JJ o FC4J
3606,6076474-3-LIBERTY,543281,CARGO 1416 ó 1516,CARGO 1416 o 1516
4225,6079017-1-LIBERTY,562771,CARGO 1630 ó 1730,CARGO 1630 o 1730
4617,6080709-3-LIBERTY,575425,CARGO 1416 ó 1516,CARGO 1416 o 1516
4768,6081372-4-LIBERTY,581588,FC114 ó FC124,FC114 o FC124
5219,6083427-1-LIBERTY,594093,RD688 ó 689,RD688 o 689
5456,6084507-1-LIBERTY,602150,FC114 ó FC124,FC114 o FC124
6626,6086193-1-LIBERTY,619475,CARGO 1630 ó 1730,CARGO 1630 o 1730
7102,6088150-1-LIBERTY,636714,CARGO 1622 ó 1722,CARGO 1622 o 1722
7103,6088150-2-LIBERTY,636715,CARGO 1416 ó 1516,CARGO 1416 o 1516
7558,6090542-1-LIBERTY,657884,CARGO 1416 ó 1516,CARGO 1416 o 1516
7565,6090542-5-LIBERTY,657962,CARGO 1622 ó 1722,CARGO 1622 o 1722
7569,6090542-9-LIBERTY,658068,1621 ó 1721,1621 o 1721
7801,6091842-1-LIBERTY,670181,CARGO 1416 ó 1516,CARGO 1416 o 1516
8079,6092398-2-LIBERTY,674779,CARGO 1622 ó 1722,CARGO 1622 o 1722
9181,6097412-1-LIBERTY,717345,CARGO 1416 ó 1516,CARGO 1416 o 1516
10238,6098306-2-LIBERTY,724677,FC114 ó FC124,FC114 o FC124
12272,61015410-2-LIBERTY,900281698,RD688 ó 689,RD688 o 689
17548,61043185-1-LIBERTY,900304601,CARGO 1622 ó 1722,CARGO 1622 o 1722
23055,6109028-1-LIBERTY,822968,CARGO 1416 ó 1516,CARGO 1416 o 1516
24987,61105797-1-LIBERTY,900635285,CARGO 1416 ó 1516,CARGO 1416 o 1516
25047,61106386-1-LIBERTY,903133503,CARGO 1416 ó 1516,CARGO 1416 o 1516
26825,61121070-1-LIBERTY,903250975,2574 ó 2575,2574 o 2575
27609,61128120-1-LIBERTY,903256014,FD195 ó FD1JL,FD195 o FD1JL
28395,6113432-1-LIBERTY,884720,FC114 ó FC124,FC114 o FC124
28971,6113865-1-LIBERTY,888491,FLB ó FLD,FLB o FLD
35208,6118543-11-LIBERTY,933496,1621 ó 1721,1621 o 1721
35215,6118543-3-LIBERTY,933189,FLB ó FLD,FLB o FLD
35216,6118543-4-LIBERTY,933202,FLB ó FLD,FLB o FLD
36295,61195977-1-LIBERTY,904386428,CARGO 1416 ó 1516,CARGO 1416 o 1516
36296,61195977-2-LIBERTY,904386429,CARGO 1416 ó 1516,CARGO 1416 o 1516
36302,61196016-1-LIBERTY,904386562,CARGO 1416 ó 1516,CARGO 1416 o 1516
36303,61196016-2-LIBERTY,904386563,CARGO 1416 ó 1516,CARGO 1416 o 1516
38435,61213734-1-LIBERTY,904354717,RD688 ó 689,RD688 o 689
42085,61235816-1-LIBERTY,904828406,CARGO 1622 ó 1722,CARGO 1622 o 1722
43449,6124649-1-LIBERTY,922076,FC144 ó FC3JJ ó FC4J,FC144 o FC3JJ o FC4J
44888,6125532-1-LIBERTY,1000125,FC144 ó FC3JJ ó FC4J,FC144 o FC3JJ o FC4J
46826,6127065-2-LIBERTY,1018193,CARGO 1416 ó 1516,CARGO 1416 o 1516
50461,61297580-1-LIBERTY,905329025,2574 ó 2575,2574 o 2575
50887,6130012-1-LIBERTY,966857,CARGO 1416 ó 1516,CARGO 1416 o 1516
50890,6130012-4-LIBERTY,1213835,CARGO 1416 ó 1516,CARGO 1416 o 1516
51151,6130213-1-LIBERTY,1055819,8100 ó 8000,8100 o 8000
51290,6130337-1-LIBERTY,969586,CARGO 1622 ó 1722,CARGO 1622 o 1722
62652,61381080-1-LIBERTY,905873734,RD688 ó 689,RD688 o 689
64037,61394177-1-LIBERTY,906118291,CARGO 1622 ó 1722,CARGO 1622 o 1722
66817,6141776-1-LIBERTY,1129741,CARGO 1630 ó 1730,CARGO 1630 o 1730

In [46]:
### NUM_MOTOR

dfp1 = dfp[['KEY', 'SSEGURO', 'NUM_MOTOR']]
dfs1 = dfs[['KEY', 'NUM_MOTOR']]

dfp1['NUM_MOTOR'] = dfp1['NUM_MOTOR'].astype(str).copy()
dfs1['NUM_MOTOR'] = dfs1['NUM_MOTOR'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.NUM_MOTOR_p != dfm.NUM_MOTOR_s) & (~dfm.NUM_MOTOR_s.isnull()) & (~dfm.NUM_MOTOR_p.isnull())].copy()
dfm1[['KEY','SSEGURO','NUM_MOTOR_p','NUM_MOTOR_s']]

<ipython-input-46-e2bf11dc8e66>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['NUM_MOTOR'] = dfp1['NUM_MOTOR'].astype(str).copy()
<ipython-input-46-e2bf11dc8e66>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['NUM_MOTOR'] = dfs1['NUM_MOTOR'].astype(str).copy()

                      KEY    SSEGURO           NUM_MOTOR_p       NUM_MOTOR_s
12855  61020627-1-LIBERTY  900302907             9D192864           9D192864
12993  61021509-1-LIBERTY  900309491  20354867                      20354867
12999  61021544-1-LIBERTY  900309493  VQ35099908C                VQ35099908C
13286  61023815-1-LIBERTY  900142365  3UZ0407601                  3UZ0407601
13455  61025516-1-LIBERTY  900306945  Z6793705                      Z6793705
...                   ...        ...                   ...               ...
65991  61411107-1-LIBERTY  906349999           3ZRA660036         3ZRA660036
65992  61411108-1-LIBERTY  906350002           1NZZ241246         1NZZ241246
66136  61412062-1-LIBERTY  906356221     BFZB55U8K8760889   BFZB55U8K8760889
66319  61413701-1-LIBERTY  906373749           2GRK515279         2GRK515279
67026  61419827-1-LIBERTY  906363063         QR25481757L         QR25481757L

[205 rows x 4 columns]

In [47]:
### CORREDOR_RUT

dfp1 = dfp[['KEY', 'SSEGURO', 'CORREDOR_RUT']]
dfs1 = dfs[['KEY', 'CORREDOR_RUT']]

dfp1['CORREDOR_RUT'] = dfp1['CORREDOR_RUT'].astype(str).copy()
dfs1['CORREDOR_RUT'] = dfs1['CORREDOR_RUT'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.CORREDOR_RUT_p != dfm.CORREDOR_RUT_s) & (~dfm.CORREDOR_RUT_s.isnull()) & (~dfm.CORREDOR_RUT_p.isnull())].copy()
dfm1[['KEY','SSEGURO','CORREDOR_RUT_p','CORREDOR_RUT_s']]

<ipython-input-47-e76bb14bb1f9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['CORREDOR_RUT'] = dfp1['CORREDOR_RUT'].astype(str).copy()
<ipython-input-47-e76bb14bb1f9>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['CORREDOR_RUT'] = dfs1['CORREDOR_RUT'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, CORREDOR_RUT_p, CORREDOR_RUT_s]
Index: []

In [48]:
### CORREDOR

dfp1 = dfp[['KEY', 'SSEGURO', 'CORREDOR']]
dfs1 = dfs[['KEY', 'CORREDOR']]

dfp1['CORREDOR'] = dfp1['CORREDOR'].astype(str).copy()
dfs1['CORREDOR'] = dfs1['CORREDOR'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.CORREDOR_p != dfm.CORREDOR_s) & (~dfm.CORREDOR_s.isnull()) & (~dfm.CORREDOR_p.isnull())].copy()
dfm1[['KEY','SSEGURO','CORREDOR_p','CORREDOR_s']]

<ipython-input-48-4740e9a018dc>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['CORREDOR'] = dfp1['CORREDOR'].astype(str).copy()
<ipython-input-48-4740e9a018dc>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['CORREDOR'] = dfs1['CORREDOR'].astype(str).copy()

,KEY,SSEGURO,CORREDOR_p,CORREDOR_s
1,6013563-9-LIBERTY,489217,SOC CORREDORES SEGSLOTA ASOCIADOS LTDA,SOC CORREDORES SEGSLOTA ASOCIADOS LTDA
5,6020240-2-LIBERTY,522698,CLAUDIO F ALARCON TORO CORREDOR SEGUROS EIRL,CLAUDIO F ALARCON TORO CORREDOR SEGUROS EIRL
6,6021066-2-LIBERTY,571770,SOC CORREDORES SEGSLOTA ASOCIADOS LTDA,SOC CORREDORES SEGSLOTA ASOCIADOS LTDA
8,6021268-2-LIBERTY,552100,JUAN MANUEL PEREZ CIA LTDA,JUAN MANUEL PEREZ CIA LTDA
9,6021792-3-LIBERTY,481161,ZUÑIGA TORO ROBERTO,ZUNIGA TORO ROBERTO ALFONSO
...,...,...,...,...
67175,6142118-1-LIBERTY,1126370,ZUÑIGA JADUR MARIO FERNANDO,ZUNIGA JADUR MARIO FERNANDO
67177,6142120-1-LIBERTY,1084756,BSTCORRDE SEGSLTDA,BSTCORRDE SEGSLTDA
67201,6142153-1-LIBERTY,1192429,MUÑOZ OYARCE GERARDO,MU?OZ OYARCE GERARDO
67206,6142160-1-LIBERTY,1129562,SOCIEDAD COMERCIAL PRODUCTORA SEGUROS VOLCAN LLAIMA LIMITADA,SOCIEDAD COMERCIAL PRODUCTORA SEGUROS VOLCAN LLAIMA LIMITADA
67208,6142163-1-LIBERTY,1192579,CORREDORA SEGUROS LA CAMARA LTDA,CORREDORA SEGUROS LA CAMARA LTDA

In [49]:
### COD_PRODUCTO

dfp1 = dfp[['KEY', 'SSEGURO', 'COD_PRODUCTO']]
dfs1 = dfs[['KEY', 'COD_PRODUCTO']]

dfp1['COD_PRODUCTO'] = dfp1['COD_PRODUCTO'].astype(str).copy()
dfs1['COD_PRODUCTO'] = dfs1['COD_PRODUCTO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COD_PRODUCTO_p != dfm.COD_PRODUCTO_s) & (~dfm.COD_PRODUCTO_s.isnull()) & (~dfm.COD_PRODUCTO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COD_PRODUCTO_p','COD_PRODUCTO_s']]

<ipython-input-49-5d73d5250523>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COD_PRODUCTO'] = dfp1['COD_PRODUCTO'].astype(str).copy()
<ipython-input-49-5d73d5250523>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COD_PRODUCTO'] = dfs1['COD_PRODUCTO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, COD_PRODUCTO_p, COD_PRODUCTO_s]
Index: []

In [50]:
### PRODUCTO

dfp1 = dfp[['KEY', 'SSEGURO', 'PRODUCTO']]
dfs1 = dfs[['KEY', 'PRODUCTO']]

dfp1['PRODUCTO'] = dfp1['PRODUCTO'].astype(str).copy()
dfs1['PRODUCTO'] = dfs1['PRODUCTO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.PRODUCTO_p != dfm.PRODUCTO_s) & (~dfm.PRODUCTO_s.isnull()) & (~dfm.PRODUCTO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','PRODUCTO_p','PRODUCTO_s']]

<ipython-input-50-ce6ea0f000c9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['PRODUCTO'] = dfp1['PRODUCTO'].astype(str).copy()
<ipython-input-50-ce6ea0f000c9>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['PRODUCTO'] = dfs1['PRODUCTO'].astype(str).copy()

,KEY,SSEGURO,PRODUCTO_p,PRODUCTO_s
86,6039529-2-LIBERTY,586715,Vehículo Security,Vehiculo Security
120,6045471-2-LIBERTY,713892,Vehículo Security,Vehiculo Security
121,6045954-2-LIBERTY,676100,Vehículo Security,Vehiculo Security
137,6048202-2-LIBERTY,586793,Vehículo Security,Vehiculo Security
272,6059163-2-LIBERTY,523375,Vehículo Security,Vehiculo Security
...,...,...,...,...
66999,61419658-1-LIBERTY,906357377,Vehículo Security,Vehiculo Security
67000,61419659-1-LIBERTY,906357374,Vehículo Security,Vehiculo Security
67013,61419765-1-LIBERTY,906408982,Vehículo Pesados Web,Vehiculo Pesados Web
67017,61419775-1-LIBERTY,906363642,César Vallejo,Cesar Vallejo
67143,61420892-1-LIBERTY,906362815,Vehículo Pesados Web,Vehiculo Pesados Web

In [51]:
### COD_PLAN

dfp1 = dfp[['KEY', 'SSEGURO', 'COD_PLAN']]
dfs1 = dfs[['KEY', 'COD_PLAN']]

dfp1['COD_PLAN'] = dfp1['COD_PLAN'].astype(str).copy()
dfs1['COD_PLAN'] = dfs1['COD_PLAN'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COD_PLAN_p != dfm.COD_PLAN_s) & (~dfm.COD_PLAN_s.isnull()) & (~dfm.COD_PLAN_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COD_PLAN_p','COD_PLAN_s']]

<ipython-input-51-c102445f3ba4>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COD_PLAN'] = dfp1['COD_PLAN'].astype(str).copy()
<ipython-input-51-c102445f3ba4>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COD_PLAN'] = dfs1['COD_PLAN'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, COD_PLAN_p, COD_PLAN_s]
Index: []

In [52]:
### PLAN

dfp1 = dfp[['KEY', 'SSEGURO', 'PLAN']]
dfs1 = dfs[['KEY', 'PLAN']]

dfp1['PLAN'] = dfp1['PLAN'].astype(str).copy()
dfs1['PLAN'] = dfs1['PLAN'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.PLAN_p != dfm.PLAN_s) & (~dfm.PLAN_s.isnull()) & (~dfm.PLAN_p.isnull())].copy()
dfm1[['KEY','SSEGURO','PLAN_p','PLAN_s']]

<ipython-input-52-c448c99da47e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['PLAN'] = dfp1['PLAN'].astype(str).copy()
<ipython-input-52-c448c99da47e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['PLAN'] = dfs1['PLAN'].astype(str).copy()

,KEY,SSEGURO,PLAN_p,PLAN_s
1846,6064855-30-LIBERTY,521977,CAMIÓN - TRACTO CAMIÓN,CAMION - TRACTO CAMION
2002,6067479-1-LIBERTY,427855,CAMIÓN - TRACTO CAMIÓN,CAMION - TRACTO CAMION
2255,6069840-1-LIBERTY,457893,CAMIÓN - TRACTO CAMIÓN,CAMION - TRACTO CAMION
2288,6070023-1-LIBERTY,459244,CAMIÓN - TRACTO CAMIÓN,CAMION - TRACTO CAMION
2393,6070627-1-LIBERTY,464820,CAMIÓN - TRACTO CAMIÓN,CAMION - TRACTO CAMION
...,...,...,...,...
67162,61421061-1-LIBERTY,906438260,VEHÍCULO PARTICULAR WEB,VEHICULO PARTICULAR WEB
67163,61421064-1-LIBERTY,906273357,VEHÍCULO PARTICULAR WEB,VEHICULO PARTICULAR WEB
67164,61421065-1-LIBERTY,906438354,VEHÍCULO PARTICULAR WEB,VEHICULO PARTICULAR WEB
67165,61421066-1-LIBERTY,906276454,DAÑOS MATERIALES PARTICULAR,DA?OS MATERIALES PARTICULAR
67166,61421076-1-LIBERTY,906279137,DAÑOS MATERIALES PARTICULAR,DA?OS MATERIALES PARTICULAR

In [53]:
### DEDUCIBLE

dfp1 = dfp[['KEY', 'SSEGURO', 'DEDUCIBLE']]
dfs1 = dfs[['KEY', 'DEDUCIBLE']]

dfp1['DEDUCIBLE'] = dfp1['DEDUCIBLE'].astype(str).copy()
dfs1['DEDUCIBLE'] = dfs1['DEDUCIBLE'].astype(float).astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.DEDUCIBLE_p != dfm.DEDUCIBLE_s) & (~dfm.DEDUCIBLE_s.isnull()) & (~dfm.DEDUCIBLE_p.isnull())].copy()
dfm1[['KEY','SSEGURO','DEDUCIBLE_p','DEDUCIBLE_s']]

<ipython-input-53-c73530feba58>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['DEDUCIBLE'] = dfp1['DEDUCIBLE'].astype(str).copy()
<ipython-input-53-c73530feba58>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['DEDUCIBLE'] = dfs1['DEDUCIBLE'].astype(float).astype(str).copy()

                      KEY    SSEGURO DEDUCIBLE_p DEDUCIBLE_s
67      6038204-4-LIBERTY     493667         0.0         5.0
196     6052574-2-LIBERTY     488202         3.0        10.0
2108    6068488-1-LIBERTY     447180         7.0         7.5
2110    6068502-1-LIBERTY     447248         0.0         3.0
2754    6072513-1-LIBERTY     485878         3.0         5.0
...                   ...        ...         ...         ...
65391  61405011-1-LIBERTY  906316484         2.0         2.5
65942   6141065-1-LIBERTY    1182155         0.0         3.0
66123  61411991-1-LIBERTY  906272604         2.0         2.5
66127  61412013-1-LIBERTY  906272620         2.0         2.5
66911  61419007-1-LIBERTY  906400472         2.0         2.5

[175 rows x 4 columns]

In [54]:
### DEDUCIBLE_INI

dfp1 = dfp[['KEY', 'SSEGURO', 'DEDUCIBLE_INI']]
dfs1 = dfs[['KEY', 'DEDUCIBLE_INI']]

dfp1['DEDUCIBLE_INI'] = dfp1['DEDUCIBLE_INI'].astype(str).copy()
dfs1['DEDUCIBLE_INI'] = dfs1['DEDUCIBLE_INI'].astype(float).astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.DEDUCIBLE_INI_p != dfm.DEDUCIBLE_INI_s) & (~dfm.DEDUCIBLE_INI_s.isnull()) & (~dfm.DEDUCIBLE_INI_p.isnull())].copy()
dfm1[['KEY','SSEGURO','DEDUCIBLE_INI_p','DEDUCIBLE_INI_s']]

<ipython-input-54-eb58386f697e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['DEDUCIBLE_INI'] = dfp1['DEDUCIBLE_INI'].astype(str).copy()
<ipython-input-54-eb58386f697e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['DEDUCIBLE_INI'] = dfs1['DEDUCIBLE_INI'].astype(float).astype(str).copy()

                       KEY    SSEGURO DEDUCIBLE_INI_p DEDUCIBLE_INI_s
2108     6068488-1-LIBERTY     447180             7.0             7.5
2551    6071439-25-LIBERTY     777566             3.0             0.0
2555    6071445-14-LIBERTY     627272             3.0             0.0
3080   6074085-310-LIBERTY     553791             1.0             0.0
3089   6074085-357-LIBERTY     741652             1.0             1.5
...                    ...        ...             ...             ...
65358   61404680-1-LIBERTY  906314830             2.0             2.5
65391   61405011-1-LIBERTY  906316484             2.0             2.5
66123   61411991-1-LIBERTY  906272604             2.0             2.5
66127   61412013-1-LIBERTY  906272620             2.0             2.5
66911   61419007-1-LIBERTY  906400472             2.0             2.5

[162 rows x 4 columns]

In [55]:
### CONTRATANTE_RUT

dfp1 = dfp[['KEY', 'SSEGURO', 'CONTRATANTE_RUT']]
dfs1 = dfs[['KEY', 'CONTRATANTE_RUT']]

dfp1['CONTRATANTE_RUT'] = dfp1['CONTRATANTE_RUT'].astype(str).copy()
dfs1['CONTRATANTE_RUT'] = dfs1['CONTRATANTE_RUT'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.CONTRATANTE_RUT_p != dfm.CONTRATANTE_RUT_s) & (~dfm.CONTRATANTE_RUT_s.isnull()) & (~dfm.CONTRATANTE_RUT_p.isnull())].copy()
dfm1[['KEY','SSEGURO','CONTRATANTE_RUT_p','CONTRATANTE_RUT_s']]

<ipython-input-55-5b690d752553>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['CONTRATANTE_RUT'] = dfp1['CONTRATANTE_RUT'].astype(str).copy()
<ipython-input-55-5b690d752553>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['CONTRATANTE_RUT'] = dfs1['CONTRATANTE_RUT'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, CONTRATANTE_RUT_p, CONTRATANTE_RUT_s]
Index: []

In [56]:
### CONTRATANTE_NOMBRE

dfp1 = dfp[['KEY', 'SSEGURO', 'CONTRATANTE_NOMBRE']]
dfs1 = dfs[['KEY', 'CONTRATANTE_NOMBRE']]

dfp1['CONTRATANTE_NOMBRE'] = dfp1['CONTRATANTE_NOMBRE'].astype(str).copy()
dfs1['CONTRATANTE_NOMBRE'] = dfs1['CONTRATANTE_NOMBRE'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.CONTRATANTE_NOMBRE_p != dfm.CONTRATANTE_NOMBRE_s) & (~dfm.CONTRATANTE_NOMBRE_s.isnull()) & (~dfm.CONTRATANTE_NOMBRE_p.isnull())].copy()
dfm1[['KEY','SSEGURO','CONTRATANTE_NOMBRE_p','CONTRATANTE_NOMBRE_s']]

<ipython-input-56-80420826be64>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['CONTRATANTE_NOMBRE'] = dfp1['CONTRATANTE_NOMBRE'].astype(str).copy()
<ipython-input-56-80420826be64>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['CONTRATANTE_NOMBRE'] = dfs1['CONTRATANTE_NOMBRE'].astype(str).copy()

,KEY,SSEGURO,CONTRATANTE_NOMBRE_p,CONTRATANTE_NOMBRE_s
2,6014329-19-LIBERTY,789926,FLEX CENTER S A,FLEX CENTER S A
22,6027603-40-LIBERTY,583019,SOC INDUSTRIAL ROMERAL S A,SOC INDUSTRIAL ROMERAL S A
39,6031896-44-LIBERTY,641110,SOC DE TRANSPORTE DE PASAJEROS MAIG Y COMPANIA LTDA,SOC DE TRANSPORTE DE PASAJEROS MAIG Y COMPANIA LTDA
48,6034386-12-LIBERTY,543288,FREUDENBERG PRODUCTOS DEL HOGAR LIMITADA,FREUDENBERG PRODUCTOS DEL HOGAR LIMITADA
55,6035919-2-LIBERTY,481966,TRANSPORTES G MARIN LIMITADA,TRANSPORTES G MARIN LIMITADA
...,...,...,...,...
67188,61421366-1-LIBERTY,906438828,RAUL RAMON DAROCH VALDES,RAUL RAMON DAROCH VALDES
67191,61421419-1-LIBERTY,906438882,TRASLAVI¿A AGUIRRE ALBANIA,TRASLAVI?A AGUIRRE ALBANIA
67202,61421551-1-LIBERTY,906439017,MU¿OZ REALE JULIO,MU?OZ REALE JULIO
67203,61421567-1-LIBERTY,906439034,CARMEN SALGADO MU#OZ,CARMEN SALGADO MU#OZ
67208,6142163-1-LIBERTY,1192579,CONSTRUCTORA PEHUENCHE LTDA,CONSTRUCTORA PEHUENCHE LTDA

In [57]:
### FLOTA1

dfp1 = dfp[['KEY', 'SSEGURO', 'FLOTA1']]
dfs1 = dfs[['KEY', 'FLOTA1']]

dfp1['FLOTA1'] = dfp1['FLOTA1'].astype(str).copy()
dfs1['FLOTA1'] = dfs1['FLOTA1'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FLOTA1_p != dfm.FLOTA1_s) & (~dfm.FLOTA1_s.isnull()) & (~dfm.FLOTA1_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FLOTA1_p','FLOTA1_s']]

<ipython-input-57-a0fde33968d5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FLOTA1'] = dfp1['FLOTA1'].astype(str).copy()
<ipython-input-57-a0fde33968d5>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FLOTA1'] = dfs1['FLOTA1'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, FLOTA1_p, FLOTA1_s]
Index: []

In [58]:
### NRO_MASIVO

dfp1 = dfp[['KEY', 'SSEGURO', 'NRO_MASIVO']]
dfs1 = dfs[['KEY', 'NRO_MASIVO']]

dfp1['NRO_MASIVO'] = dfp1['NRO_MASIVO'].astype(str).copy()
dfs1['NRO_MASIVO'] = dfs1['NRO_MASIVO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.NRO_MASIVO_p != dfm.NRO_MASIVO_s) & (~dfm.NRO_MASIVO_s.isnull()) & (~dfm.NRO_MASIVO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','NRO_MASIVO_p','NRO_MASIVO_s']]

<ipython-input-58-3c3c006bf25f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['NRO_MASIVO'] = dfp1['NRO_MASIVO'].astype(str).copy()
<ipython-input-58-3c3c006bf25f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['NRO_MASIVO'] = dfs1['NRO_MASIVO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, NRO_MASIVO_p, NRO_MASIVO_s]
Index: []

In [59]:
### PRIMA

dfp1 = dfp[['KEY', 'SSEGURO', 'PRIMA']]
dfs1 = dfs[['KEY', 'PRIMA']]

dfp1['PRIMA'] = dfp1['PRIMA'].astype(str).copy()
dfs1['PRIMA'] = dfs1['PRIMA'].astype(float).astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.PRIMA_p != dfm.PRIMA_s) & (~dfm.PRIMA_s.isnull()) & (~dfm.PRIMA_p.isnull())].copy()
dfm1[['KEY','SSEGURO','PRIMA_p','PRIMA_s']]

<ipython-input-59-bebf42a9ea5d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['PRIMA'] = dfp1['PRIMA'].astype(str).copy()
<ipython-input-59-bebf42a9ea5d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['PRIMA'] = dfs1['PRIMA'].astype(float).astype(str).copy()

                       KEY  SSEGURO        PRIMA_p       PRIMA_s
153    6049507-350-LIBERTY   571163   1.9777664761  1.9777664762
155    6049507-366-LIBERTY   827708   1.9777664761  1.9777664762
156    6049507-379-LIBERTY   828250   1.9777664761  1.9777664762
157    6049507-382-LIBERTY  1328247   1.7972704969   1.797270497
158    6049507-387-LIBERTY  1328376   1.7378808462  1.7378808463
162    6049507-399-LIBERTY  1340221   1.6753116175  1.6753116176
163    6049507-400-LIBERTY  1340241   2.0341484438  2.0341484439
165    6049507-402-LIBERTY  1341071   2.0281765689   2.028176569
167    6049507-405-LIBERTY  1341097   1.7089039158  1.7089039159
168    6049507-412-LIBERTY  1341439   2.0055019904  2.0055019905
171    6049507-417-LIBERTY  1497809    1.638061054  1.6380610541
172    6049507-418-LIBERTY  1497817    1.638061054  1.6380610541
21674    6107751-1-LIBERTY   727334  12.9247674652  12.924767466

In [60]:
### PRIMA_TARIFA

dfp1 = dfp[['KEY', 'SSEGURO', 'PRIMA_TARIFA']]
dfs1 = dfs[['KEY', 'PRIMA_TARIFA']]

dfp1['PRIMA_TARIFA'] = dfp1['PRIMA_TARIFA'].astype(str).copy()
dfs1['PRIMA_TARIFA'] = dfs1['PRIMA_TARIFA'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.PRIMA_TARIFA_p != dfm.PRIMA_TARIFA_s) & (~dfm.PRIMA_TARIFA_s.isnull()) & (~dfm.PRIMA_TARIFA_p.isnull())].copy()
dfm1[['KEY','SSEGURO','PRIMA_TARIFA_p','PRIMA_TARIFA_s']]

<ipython-input-60-9f3b977d4761>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['PRIMA_TARIFA'] = dfp1['PRIMA_TARIFA'].astype(str).copy()
<ipython-input-60-9f3b977d4761>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['PRIMA_TARIFA'] = dfs1['PRIMA_TARIFA'].astype(str).copy()

                       KEY    SSEGURO PRIMA_TARIFA_p PRIMA_TARIFA_s
1        6013563-9-LIBERTY     489217           23.0             23
130      6047174-2-LIBERTY     698595           31.0             31
154    6049507-362-LIBERTY     817363   1.4819056663   1.4819056664
155    6049507-366-LIBERTY     827708   0.6600310867   0.6600310868
156    6049507-379-LIBERTY     828250   0.4371768772   0.4371768773
...                    ...        ...            ...            ...
66895   61418797-1-LIBERTY  906399895           16.0             16
66900   61418858-1-LIBERTY  906399958           16.0             16
66902   61418896-1-LIBERTY  906400037           16.0             16
67103   61420573-1-LIBERTY  906435659           11.0             11
67158   61421040-1-LIBERTY  906361885           13.0             13

[964 rows x 4 columns]

In [61]:
### DESCUENTO

dfp1 = dfp[['KEY', 'SSEGURO', 'DESCUENTO']]
dfs1 = dfs[['KEY', 'DESCUENTO']]

dfp1['DESCUENTO'] = dfp1['DESCUENTO'].astype(str).copy()
dfs1['DESCUENTO'] = dfs1['DESCUENTO'].astype(float).astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.DESCUENTO_p != dfm.DESCUENTO_s) & (~dfm.DESCUENTO_s.isnull()) & (~dfm.DESCUENTO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','DESCUENTO_p','DESCUENTO_s']]

<ipython-input-61-618017a888e1>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['DESCUENTO'] = dfp1['DESCUENTO'].astype(str).copy()
<ipython-input-61-618017a888e1>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['DESCUENTO'] = dfs1['DESCUENTO'].astype(float).astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, DESCUENTO_p, DESCUENTO_s]
Index: []

In [62]:
### COMISION

dfp1 = dfp[['KEY', 'SSEGURO', 'COMISION']]
dfs1 = dfs[['KEY', 'COMISION']]

dfp1['COMISION'] = dfp1['COMISION'].astype(str).copy()
dfs1['COMISION'] = dfs1['COMISION'].astype(float).astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COMISION_p != dfm.COMISION_s) & (~dfm.COMISION_s.isnull()) & (~dfm.COMISION_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COMISION_p','COMISION_s']]

<ipython-input-62-0323381b2499>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COMISION'] = dfp1['COMISION'].astype(str).copy()
<ipython-input-62-0323381b2499>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COMISION'] = dfs1['COMISION'].astype(float).astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, COMISION_p, COMISION_s]
Index: []

In [63]:
### PRIMA_FINAL

dfp1 = dfp[['KEY', 'SSEGURO', 'PRIMA_FINAL']]
dfs1 = dfs[['KEY', 'PRIMA_FINAL']]

dfp1['PRIMA_FINAL'] = dfp1['PRIMA_FINAL'].astype(str).copy()
dfs1['PRIMA_FINAL'] = dfs1['PRIMA_FINAL'].astype(float).astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.PRIMA_FINAL_p != dfm.PRIMA_FINAL_s) & (~dfm.PRIMA_FINAL_s.isnull()) & (~dfm.PRIMA_FINAL_p.isnull())].copy()
dfm1[['KEY','SSEGURO','PRIMA_FINAL_p','PRIMA_FINAL_s']]

<ipython-input-63-ddc52a9e7869>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['PRIMA_FINAL'] = dfp1['PRIMA_FINAL'].astype(str).copy()
<ipython-input-63-ddc52a9e7869>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['PRIMA_FINAL'] = dfs1['PRIMA_FINAL'].astype(float).astype(str).copy()

                       KEY  SSEGURO  PRIMA_FINAL_p PRIMA_FINAL_s
153    6049507-350-LIBERTY   571163   1.9777664761  1.9777664762
155    6049507-366-LIBERTY   827708   1.9777664761  1.9777664762
156    6049507-379-LIBERTY   828250   1.9777664761  1.9777664762
157    6049507-382-LIBERTY  1328247   1.7972704969   1.797270497
158    6049507-387-LIBERTY  1328376   1.7378808462  1.7378808463
162    6049507-399-LIBERTY  1340221   1.6753116175  1.6753116176
163    6049507-400-LIBERTY  1340241   1.7093102409   1.709310241
165    6049507-402-LIBERTY  1341071   2.0281765689   2.028176569
167    6049507-405-LIBERTY  1341097   1.7089039158  1.7089039159
168    6049507-412-LIBERTY  1341439   2.0055019904  2.0055019905
171    6049507-417-LIBERTY  1497809    1.638061054  1.6380610541
172    6049507-418-LIBERTY  1497817    1.638061054  1.6380610541
21674    6107751-1-LIBERTY   727334  12.9247674652  12.924767466

In [64]:
### COD_ENDOSO

dfp1 = dfp[['KEY', 'SSEGURO', 'COD_ENDOSO']]
dfs1 = dfs[['KEY', 'COD_ENDOSO']]

dfp1['COD_ENDOSO'] = dfp1['COD_ENDOSO'].astype(str).copy()
dfs1['COD_ENDOSO'] = dfs1['COD_ENDOSO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COD_ENDOSO_p != dfm.COD_ENDOSO_s) & (~dfm.COD_ENDOSO_s.isnull()) & (~dfm.COD_ENDOSO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COD_ENDOSO_p','COD_ENDOSO_s']]

<ipython-input-64-b712b89b35d7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COD_ENDOSO'] = dfp1['COD_ENDOSO'].astype(str).copy()
<ipython-input-64-b712b89b35d7>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COD_ENDOSO'] = dfs1['COD_ENDOSO'].astype(str).copy()

                      KEY    SSEGURO COD_ENDOSO_p COD_ENDOSO_s
63462  61388119-1-LIBERTY  906118132          375          100
64687  61399366-1-LIBERTY  906118346          803          100
66679  61416374-1-LIBERTY  906358167          269          325

In [65]:
### TDESCRIP

dfp1 = dfp[['KEY', 'SSEGURO', 'TDESCRIP']]
dfs1 = dfs[['KEY', 'TDESCRIP']]

dfp1['TDESCRIP'] = dfp1['TDESCRIP'].astype(str).copy()
dfs1['TDESCRIP'] = dfs1['TDESCRIP'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.TDESCRIP_p != dfm.TDESCRIP_s) & (~dfm.TDESCRIP_s.isnull()) & (~dfm.TDESCRIP_p.isnull())].copy()
dfm1[['KEY','SSEGURO','TDESCRIP_p','TDESCRIP_s']]

<ipython-input-65-781ba4762390>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['TDESCRIP'] = dfp1['TDESCRIP'].astype(str).copy()
<ipython-input-65-781ba4762390>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['TDESCRIP'] = dfs1['TDESCRIP'].astype(str).copy()

,KEY,SSEGURO,TDESCRIP_p,TDESCRIP_s
7,6021077-2-LIBERTY,581703,SE INCLUYE PATENTE DEL VEHICULO ASEGURADO.- DEBE DECIR : CJZL-27,\nSE INCLUYE PATENTE DEL VEHICULO ASEGURADO.-\n\nDEBE DECIR : CJZL-27
51,6034842-2-LIBERTY,566010,"SE DEJA CONSTANCIA Y A SOLICITUD DEL ASEGURADO, SE EFECTUAN LAS SIGUIENTES MODIFICACIONES : - ...","SE DEJA CONSTANCIA Y A SOLICITUD DEL ASEGURADO, SE EFECTUAN LAS SIGUIENTES MODIFICACIONES :\n\n-..."
55,6035919-2-LIBERTY,481966,"NOTA: SE DEJA CONSTANCIA QUE DESDE EL INICIO DE LA VIGENCIA, EL PRESENTE ITEM RIGE A FAVOR DEL ...","NOTA:\nSE DEJA CONSTANCIA QUE DESDE EL INICIO DE LA VIGENCIA, EL PRESENTE ITEM RIGE A FAVOR DEL ..."
67,6038204-4-LIBERTY,493667,SE DEJA CONSTANCIA QUE A SOLICITUD DE LA COMPAÑIA SE PROCEDE A REALIZAR LA SIGUEINTE MODIFICACI...,SE DEJA CONSTANCIA QUE A SOLICITUD DE LA COMPA?IA SE PROCEDE A REALIZAR LA SIGUEINTE MODIFICACIO...
94,6041270-3-LIBERTY,587696,SE DEJA CONSTANCIA QUE SE INCORPORA PATENTE DEL VEHICULO. OTRAS MODIFICACIONES NO HAY. FOLIO 3...,SE DEJA CONSTANCIA QUE SE INCORPORA PATENTE DEL VEHICULO.\n\nOTRAS MODIFICACIONES NO HAY.\nFOLIO...
...,...,...,...,...
67175,6142118-1-LIBERTY,1126370,Renovación de cartera,Renovacion de cartera
67177,6142120-1-LIBERTY,1084756,Renovación de cartera,Renovacion de cartera
67183,6142125-1-LIBERTY,1126412,Renovación de cartera,Renovacion de cartera
67195,61421468-1-LIBERTY,906438931,MEDIANTE EL PRESENTE ENDOSO SE MODIFICA PATENTE (CASO RECIBIDO POR BUZON REGISTRO DE PATENTE EN...,MEDIANTE EL PRESENTE ENDOSO SE MODIFICA PATENTE (CASO RECIBIDO POR BUZON REGISTRO DE PATENTE EN ...
67207,61421608-1-LIBERTY,906439077,SE ANULA POLIZA A SOLICITUD DEL ASEGURADO,\nSE ANULA POLIZA A SOLICITUD DEL ASEGURADO

In [66]:
### ENDOSO_AGRUP

dfp1 = dfp[['KEY', 'SSEGURO', 'ENDOSO_AGRUP']]
dfs1 = dfs[['KEY', 'ENDOSO_AGRUP']]

dfp1['ENDOSO_AGRUP'] = dfp1['ENDOSO_AGRUP'].astype(str).copy()
dfs1['ENDOSO_AGRUP'] = dfs1['ENDOSO_AGRUP'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.ENDOSO_AGRUP_p != dfm.ENDOSO_AGRUP_s) & (~dfm.ENDOSO_AGRUP_s.isnull()) & (~dfm.ENDOSO_AGRUP_p.isnull())].copy()
dfm1[['KEY','SSEGURO','ENDOSO_AGRUP_p','ENDOSO_AGRUP_s']]

<ipython-input-66-7ef34a7dc040>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['ENDOSO_AGRUP'] = dfp1['ENDOSO_AGRUP'].astype(str).copy()
<ipython-input-66-7ef34a7dc040>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['ENDOSO_AGRUP'] = dfs1['ENDOSO_AGRUP'].astype(str).copy()

                      KEY    SSEGURO ENDOSO_AGRUP_p ENDOSO_AGRUP_s
63462  61388119-1-LIBERTY  906118132    CANCELACION     NUEVA PROD
64687  61399366-1-LIBERTY  906118346         AJUSTE     NUEVA PROD
66679  61416374-1-LIBERTY  906358167    OTRO ENDOSO    CANCELACION

In [67]:
### NOMBRE_CONVENIO

dfp1 = dfp[['KEY', 'SSEGURO', 'NOMBRE_CONVENIO']]
dfs1 = dfs[['KEY', 'NOMBRE_CONVENIO']]

dfp1['NOMBRE_CONVENIO'] = dfp1['NOMBRE_CONVENIO'].astype(str).copy()
dfs1['NOMBRE_CONVENIO'] = dfs1['NOMBRE_CONVENIO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.NOMBRE_CONVENIO_p != dfm.NOMBRE_CONVENIO_s) & (~dfm.NOMBRE_CONVENIO_s.isnull()) & (~dfm.NOMBRE_CONVENIO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','NOMBRE_CONVENIO_p','NOMBRE_CONVENIO_s']]

<ipython-input-67-46bae265ead6>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['NOMBRE_CONVENIO'] = dfp1['NOMBRE_CONVENIO'].astype(str).copy()
<ipython-input-67-46bae265ead6>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['NOMBRE_CONVENIO'] = dfs1['NOMBRE_CONVENIO'].astype(str).copy()

,KEY,SSEGURO,NOMBRE_CONVENIO_p,NOMBRE_CONVENIO_s
2895,6073184-1-LIBERTY,490618,RENOVACION CONCESIONARIOS ARTURO ZUÑIGA,RENOVACION CONCESIONARIOS ARTURO ZU?IGA
3125,6074243-1-LIBERTY,521989,RENOVACION CONCESIONARIOS ARTURO ZUÑIGA,RENOVACION CONCESIONARIOS ARTURO ZU?IGA
3429,6075701-1-LIBERTY,536703,RENOVACION CONCESIONARIOS ARTURO ZUÑIGA,RENOVACION CONCESIONARIOS ARTURO ZU?IGA
3480,6075927-1-LIBERTY,538652,RENOVACION CONCESIONARIOS ARTURO ZUÑIGA,RENOVACION CONCESIONARIOS ARTURO ZU?IGA
4187,6078834-1-LIBERTY,561097,RENOVACION CONCESIONARIOS ARTURO ZUÑIGA,RENOVACION CONCESIONARIOS ARTURO ZU?IGA
...,...,...,...,...
66998,61419655-1-LIBERTY,906357364,"""""""SECURITY PREMIUM""""""","""SECURITY PREMIUM"""
66999,61419658-1-LIBERTY,906357377,"""""""SECURITY PREMIUM""""""","""SECURITY PREMIUM"""
67000,61419659-1-LIBERTY,906357374,"""""""SECURITY PREMIUM""""""","""SECURITY PREMIUM"""
67031,61419845-1-LIBERTY,906273271,ORBITAL LÍNEAS PERSONALES - PREMIUM,ORBITAL LINEAS PERSONALES - PREMIUM
67107,61420597-1-LIBERTY,906357228,"""""""SECURITY PREMIUM""""""","""SECURITY PREMIUM"""

In [68]:
### FLOTA_CONVENIO

dfp1 = dfp[['KEY', 'SSEGURO', 'FLOTA_CONVENIO']]
dfs1 = dfs[['KEY', 'FLOTA_CONVENIO']]

dfp1['FLOTA_CONVENIO'] = dfp1['FLOTA_CONVENIO'].astype(str).copy()
dfs1['FLOTA_CONVENIO'] = dfs1['FLOTA_CONVENIO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FLOTA_CONVENIO_p != dfm.FLOTA_CONVENIO_s) & (~dfm.FLOTA_CONVENIO_s.isnull()) & (~dfm.FLOTA_CONVENIO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FLOTA_CONVENIO_p','FLOTA_CONVENIO_s']]

<ipython-input-68-60b037ac8504>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FLOTA_CONVENIO'] = dfp1['FLOTA_CONVENIO'].astype(str).copy()
<ipython-input-68-60b037ac8504>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FLOTA_CONVENIO'] = dfs1['FLOTA_CONVENIO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, FLOTA_CONVENIO_p, FLOTA_CONVENIO_s]
Index: []

In [69]:
### SUCURSAL

dfp1 = dfp[['KEY', 'SSEGURO', 'SUCURSAL']]
dfs1 = dfs[['KEY', 'SUCURSAL']]

dfp1['SUCURSAL'] = dfp1['SUCURSAL'].astype(str).copy()
dfs1['SUCURSAL'] = dfs1['SUCURSAL'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.SUCURSAL_p != dfm.SUCURSAL_s) & (~dfm.SUCURSAL_s.isnull()) & (~dfm.SUCURSAL_p.isnull())].copy()
dfm1[['KEY','SSEGURO','SUCURSAL_p','SUCURSAL_s']]

<ipython-input-69-b990db90ab68>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['SUCURSAL'] = dfp1['SUCURSAL'].astype(str).copy()
<ipython-input-69-b990db90ab68>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['SUCURSAL'] = dfs1['SUCURSAL'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, SUCURSAL_p, SUCURSAL_s]
Index: []

In [70]:
### COD_SUCURSAL1

dfp1 = dfp[['KEY', 'SSEGURO', 'COD_SUCURSAL1']]
dfs1 = dfs[['KEY', 'COD_SUCURSAL1']]

dfp1['COD_SUCURSAL1'] = dfp1['COD_SUCURSAL1'].astype(str).copy()
dfs1['COD_SUCURSAL1'] = dfs1['COD_SUCURSAL1'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COD_SUCURSAL1_p != dfm.COD_SUCURSAL1_s) & (~dfm.COD_SUCURSAL1_s.isnull()) & (~dfm.COD_SUCURSAL1_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COD_SUCURSAL1_p','COD_SUCURSAL1_s']]

<ipython-input-70-2bbabe0ce866>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COD_SUCURSAL1'] = dfp1['COD_SUCURSAL1'].astype(str).copy()
<ipython-input-70-2bbabe0ce866>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COD_SUCURSAL1'] = dfs1['COD_SUCURSAL1'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, COD_SUCURSAL1_p, COD_SUCURSAL1_s]
Index: []

In [71]:
### SUMA_ASEG_RC

dfp1 = dfp[['KEY', 'SSEGURO', 'SUMA_ASEG_RC']]
dfs1 = dfs[['KEY', 'SUMA_ASEG_RC']]

dfp1['SUMA_ASEG_RC'] = corregirColumna(dfp1,'SUMA_ASEG_RC')

dfp1['SUMA_ASEG_RC'] = dfp1['SUMA_ASEG_RC'].astype(float).astype(str).copy()
dfs1['SUMA_ASEG_RC'] = dfs1['SUMA_ASEG_RC'].astype(float).astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.SUMA_ASEG_RC_p != dfm.SUMA_ASEG_RC_s) & (~dfm.SUMA_ASEG_RC_s.isnull()) & (~dfm.SUMA_ASEG_RC_p.isnull())].copy()
dfm1[['KEY','SSEGURO','SUMA_ASEG_RC_p','SUMA_ASEG_RC_s']]

<ipython-input-71-14f9530cc454>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['SUMA_ASEG_RC'] = corregirColumna(dfp1,'SUMA_ASEG_RC')
<ipython-input-71-14f9530cc454>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['SUMA_ASEG_RC'] = dfp1['SUMA_ASEG_RC'].astype(float).astype(str).copy()
<ipython-input-71-14f9530cc454>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['SUMA_ASEG_RC'] = dfs1['SUMA_ASEG_RC'].astype(float).astype(str).copy()

                       KEY  SSEGURO SUMA_ASEG_RC_p SUMA_ASEG_RC_s
153    6049507-350-LIBERTY   571163         1551.0        1551.19
154    6049507-362-LIBERTY   817363         1516.0         1516.8
155    6049507-366-LIBERTY   827708         1551.0        1551.19
156    6049507-379-LIBERTY   828250         1551.0        1551.19
157    6049507-382-LIBERTY  1328247         1409.0       1409.624
...                    ...      ...            ...            ...
58449   6134434-49-LIBERTY  1296662          697.0         697.19
58450   6134434-55-LIBERTY  1296879          714.0         714.16
58452   6134434-69-LIBERTY  1343743         1107.0        1107.41
58454   6134434-80-LIBERTY  1399301          708.0         708.43
58456   6134434-98-LIBERTY  1451462         1100.0        1100.98

[1062 rows x 4 columns]

In [72]:
### ORIGEN

dfp1 = dfp[['KEY', 'SSEGURO', 'ORIGEN']]
dfs1 = dfs[['KEY', 'ORIGEN']]

dfp1['ORIGEN'] = dfp1['ORIGEN'].astype(str).copy()
dfs1['ORIGEN'] = dfs1['ORIGEN'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.ORIGEN_p != dfm.ORIGEN_s) & (~dfm.ORIGEN_s.isnull()) & (~dfm.ORIGEN_p.isnull())].copy()
dfm1[['KEY','SSEGURO','ORIGEN_p','ORIGEN_s']]

<ipython-input-72-54b2ea574e1d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['ORIGEN'] = dfp1['ORIGEN'].astype(str).copy()
<ipython-input-72-54b2ea574e1d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['ORIGEN'] = dfs1['ORIGEN'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, ORIGEN_p, ORIGEN_s]
Index: []

In [73]:
### ASEGURADO_RUT

dfp1 = dfp[['KEY', 'SSEGURO', 'ASEGURADO_RUT']]
dfs1 = dfs[['KEY', 'ASEGURADO_RUT']]

dfp1['ASEGURADO_RUT'] = dfp1['ASEGURADO_RUT'].astype(str).copy()
dfs1['ASEGURADO_RUT'] = dfs1['ASEGURADO_RUT'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.ASEGURADO_RUT_p != dfm.ASEGURADO_RUT_s) & (~dfm.ASEGURADO_RUT_s.isnull()) & (~dfm.ASEGURADO_RUT_p.isnull())].copy()
dfm1[['KEY','SSEGURO','ASEGURADO_RUT_p','ASEGURADO_RUT_s']]

<ipython-input-73-eb50a5ad1d04>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['ASEGURADO_RUT'] = dfp1['ASEGURADO_RUT'].astype(str).copy()
<ipython-input-73-eb50a5ad1d04>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['ASEGURADO_RUT'] = dfs1['ASEGURADO_RUT'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, ASEGURADO_RUT_p, ASEGURADO_RUT_s]
Index: []

In [74]:
### ANO_REF_INI

dfp1 = dfp[['KEY', 'SSEGURO', 'ANO_REF_INI']]
dfs1 = dfs[['KEY', 'ANO_REF_INI']]

dfp1['ANO_REF_INI'] = dfp1['ANO_REF_INI'].astype(str).copy()
dfs1['ANO_REF_INI'] = dfs1['ANO_REF_INI'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.ANO_REF_INI_p != dfm.ANO_REF_INI_s) & (~dfm.ANO_REF_INI_s.isnull()) & (~dfm.ANO_REF_INI_p.isnull())].copy()
dfm1[['KEY','SSEGURO','ANO_REF_INI_p','ANO_REF_INI_s']]

<ipython-input-74-13195ec06317>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['ANO_REF_INI'] = dfp1['ANO_REF_INI'].astype(str).copy()
<ipython-input-74-13195ec06317>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['ANO_REF_INI'] = dfs1['ANO_REF_INI'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, ANO_REF_INI_p, ANO_REF_INI_s]
Index: []

In [75]:
### NUM_ITEMS_CONTRA

dfp1 = dfp[['KEY', 'SSEGURO', 'NUM_ITEMS_CONTRA']]
dfs1 = dfs[['KEY', 'NUM_ITEMS_CONTRA']]

dfp1['NUM_ITEMS_CONTRA'] = dfp1['NUM_ITEMS_CONTRA'].astype(str).copy()
dfs1['NUM_ITEMS_CONTRA'] = dfs1['NUM_ITEMS_CONTRA'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.NUM_ITEMS_CONTRA_p != dfm.NUM_ITEMS_CONTRA_s) & (~dfm.NUM_ITEMS_CONTRA_s.isnull()) & (~dfm.NUM_ITEMS_CONTRA_p.isnull())].copy()
dfm1[['KEY','SSEGURO','NUM_ITEMS_CONTRA_p','NUM_ITEMS_CONTRA_s']]

<ipython-input-75-892f885395c7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['NUM_ITEMS_CONTRA'] = dfp1['NUM_ITEMS_CONTRA'].astype(str).copy()
<ipython-input-75-892f885395c7>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['NUM_ITEMS_CONTRA'] = dfs1['NUM_ITEMS_CONTRA'].astype(str).copy()

                        KEY    SSEGURO NUM_ITEMS_CONTRA_p NUM_ITEMS_CONTRA_s
23800   61097783-20-LIBERTY  907093899               2171               2166
23907  61098290-634-LIBERTY  907013745               2171               2166
23908  61098290-642-LIBERTY  907013767               2171               2166
23909  61098290-664-LIBERTY  907013834               2171               2166
23910  61098290-694-LIBERTY  907093754               2171               2166
...                     ...        ...                ...                ...
35255   61185635-36-LIBERTY  907278283               2523               2497
35259   61185637-35-LIBERTY  907199386               2523               2497
35260   61185637-48-LIBERTY  907372226               2523               2497
41262   61227681-44-LIBERTY  907042282               2171               2166
64168    61395218-5-LIBERTY  907025593               2523               2497

[193 rows x 4 columns]

In [76]:
### FLOTA_CONTRA

dfp1 = dfp[['KEY', 'SSEGURO', 'FLOTA_CONTRA']]
dfs1 = dfs[['KEY', 'FLOTA_CONTRA']]

dfp1['FLOTA_CONTRA'] = dfp1['FLOTA_CONTRA'].astype(str).copy()
dfs1['FLOTA_CONTRA'] = dfs1['FLOTA_CONTRA'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FLOTA_CONTRA_p != dfm.FLOTA_CONTRA_s) & (~dfm.FLOTA_CONTRA_s.isnull()) & (~dfm.FLOTA_CONTRA_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FLOTA_CONTRA_p','FLOTA_CONTRA_s']]

<ipython-input-76-6bad8fd9b35b>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FLOTA_CONTRA'] = dfp1['FLOTA_CONTRA'].astype(str).copy()
<ipython-input-76-6bad8fd9b35b>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FLOTA_CONTRA'] = dfs1['FLOTA_CONTRA'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, FLOTA_CONTRA_p, FLOTA_CONTRA_s]
Index: []

In [77]:
### COD_CONVENIO

dfp1 = dfp[['KEY', 'SSEGURO', 'COD_CONVENIO']]
dfs1 = dfs[['KEY', 'COD_CONVENIO']]

dfp1['COD_CONVENIO'] = dfp1['COD_CONVENIO'].astype(str).copy()
dfs1['COD_CONVENIO'] = dfs1['COD_CONVENIO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COD_CONVENIO_p != dfm.COD_CONVENIO_s) & (~dfm.COD_CONVENIO_s.isnull()) & (~dfm.COD_CONVENIO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COD_CONVENIO_p','COD_CONVENIO_s']]

<ipython-input-77-e1fa72f07763>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COD_CONVENIO'] = dfp1['COD_CONVENIO'].astype(str).copy()
<ipython-input-77-e1fa72f07763>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COD_CONVENIO'] = dfs1['COD_CONVENIO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, COD_CONVENIO_p, COD_CONVENIO_s]
Index: []

In [78]:
### FLOTA

dfp1 = dfp[['KEY', 'SSEGURO', 'FLOTA']]
dfs1 = dfs[['KEY', 'FLOTA']]

dfp1['FLOTA'] = dfp1['FLOTA'].astype(str).copy()
dfs1['FLOTA'] = dfs1['FLOTA'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FLOTA_p != dfm.FLOTA_s) & (~dfm.FLOTA_s.isnull()) & (~dfm.FLOTA_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FLOTA_p','FLOTA_s']]

<ipython-input-78-b4f57070d804>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FLOTA'] = dfp1['FLOTA'].astype(str).copy()
<ipython-input-78-b4f57070d804>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FLOTA'] = dfs1['FLOTA'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, FLOTA_p, FLOTA_s]
Index: []

In [79]:
### COD_SUCURSAL

dfp1 = dfp[['KEY', 'SSEGURO', 'COD_SUCURSAL']]
dfs1 = dfs[['KEY', 'COD_SUCURSAL']]

dfp1['COD_SUCURSAL'] = dfp1['COD_SUCURSAL'].astype(str).copy()
dfs1['COD_SUCURSAL'] = dfs1['COD_SUCURSAL'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COD_SUCURSAL_p != dfm.COD_SUCURSAL_s) & (~dfm.COD_SUCURSAL_s.isnull()) & (~dfm.COD_SUCURSAL_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COD_SUCURSAL_p','COD_SUCURSAL_s']]

<ipython-input-79-80f4d25b5b5f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COD_SUCURSAL'] = dfp1['COD_SUCURSAL'].astype(str).copy()
<ipython-input-79-80f4d25b5b5f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COD_SUCURSAL'] = dfs1['COD_SUCURSAL'].astype(str).copy()

                      KEY    SSEGURO COD_SUCURSAL_p COD_SUCURSAL_s
3       6014916-2-LIBERTY     467783            499             **
10      6021800-2-LIBERTY     624242            380             **
14      6025091-2-LIBERTY     569108            430             **
15      6025319-2-LIBERTY     491475            380             **
17     6026427-15-LIBERTY     541410            380             **
...                   ...        ...            ...            ...
67159  61421045-1-LIBERTY  906275054            599             **
67162  61421061-1-LIBERTY  906438260            499             **
67165  61421066-1-LIBERTY  906276454            699             **
67206   6142160-1-LIBERTY    1129562            615             **
67208   6142163-1-LIBERTY    1192579            499             **

[18080 rows x 4 columns]

In [80]:
### LC_MODEL

dfp1 = dfp[['KEY', 'SSEGURO', 'LC_MODEL']]
dfs1 = dfs[['KEY', 'LC_MODEL']]

dfp1['LC_MODEL'] = dfp1['LC_MODEL'].astype(str).copy()
dfs1['LC_MODEL'] = dfs1['LC_MODEL'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.LC_MODEL_p != dfm.LC_MODEL_s) & (~dfm.LC_MODEL_s.isnull()) & (~dfm.LC_MODEL_p.isnull())].copy()
dfm1[['KEY','SSEGURO','LC_MODEL_p','LC_MODEL_s']]

<ipython-input-80-382a945a58db>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['LC_MODEL'] = dfp1['LC_MODEL'].astype(str).copy()
<ipython-input-80-382a945a58db>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['LC_MODEL'] = dfs1['LC_MODEL'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, LC_MODEL_p, LC_MODEL_s]
Index: []

In [81]:
### LC_MODEL_DEF

dfp1 = dfp[['KEY', 'SSEGURO', 'LC_MODEL_DEF']]
dfs1 = dfs[['KEY', 'LC_MODEL_DEF']]

dfp1['LC_MODEL_DEF'] = dfp1['LC_MODEL_DEF'].astype(str).copy()
dfs1['LC_MODEL_DEF'] = dfs1['LC_MODEL_DEF'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.LC_MODEL_DEF_p != dfm.LC_MODEL_DEF_s) & (~dfm.LC_MODEL_DEF_s.isnull()) & (~dfm.LC_MODEL_DEF_p.isnull())].copy()
dfm1[['KEY','SSEGURO','LC_MODEL_DEF_p','LC_MODEL_DEF_s']]

<ipython-input-81-d85688c2b154>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['LC_MODEL_DEF'] = dfp1['LC_MODEL_DEF'].astype(str).copy()
<ipython-input-81-d85688c2b154>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['LC_MODEL_DEF'] = dfs1['LC_MODEL_DEF'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, LC_MODEL_DEF_p, LC_MODEL_DEF_s]
Index: []

In [82]:
### MES_REF_INI

dfp1 = dfp[['KEY', 'SSEGURO', 'MES_REF_INI']]
dfs1 = dfs[['KEY', 'MES_REF_INI']]

dfp1['MES_REF_INI'] = dfp1['MES_REF_INI'].astype(str).copy()
dfs1['MES_REF_INI'] = dfs1['MES_REF_INI'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.MES_REF_INI_p != dfm.MES_REF_INI_s) & (~dfm.MES_REF_INI_s.isnull()) & (~dfm.MES_REF_INI_p.isnull())].copy()
dfm1[['KEY','SSEGURO','MES_REF_INI_p','MES_REF_INI_s']]

<ipython-input-82-9c8340ece83e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['MES_REF_INI'] = dfp1['MES_REF_INI'].astype(str).copy()
<ipython-input-82-9c8340ece83e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['MES_REF_INI'] = dfs1['MES_REF_INI'].astype(str).copy()

                       KEY    SSEGURO MES_REF_INI_p MES_REF_INI_s
0      6006870-111-LIBERTY     668744        201005           nan
1        6013563-9-LIBERTY     489217        201001           nan
2       6014329-19-LIBERTY     789926        201003           nan
3        6014916-2-LIBERTY     467783        201001           nan
4        6016183-6-LIBERTY     477975        201001           nan
...                    ...        ...           ...           ...
67206    6142160-1-LIBERTY    1129562        201103           nan
67207   61421608-1-LIBERTY  906439077        202108           nan
67208    6142163-1-LIBERTY    1192579        201101           nan
67209   61421638-1-LIBERTY  906439107        202108           nan
67210   61421658-1-LIBERTY  906439127        202108           nan

[67211 rows x 4 columns]

In [83]:
### PRIMA_RECIBO

dfp1 = dfp[['KEY', 'SSEGURO', 'PRIMA_RECIBO']]
dfs1 = dfs[['KEY', 'PRIMA_RECIBO']]

dfp1['PRIMA_RECIBO'] = dfp1['PRIMA_RECIBO'].astype(str).copy()
dfs1['PRIMA_RECIBO'] = dfs1['PRIMA_RECIBO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.PRIMA_RECIBO_p != dfm.PRIMA_RECIBO_s) & (~dfm.PRIMA_RECIBO_s.isnull()) & (~dfm.PRIMA_RECIBO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','PRIMA_RECIBO_p','PRIMA_RECIBO_s']]

<ipython-input-83-92a8092d607c>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['PRIMA_RECIBO'] = dfp1['PRIMA_RECIBO'].astype(str).copy()
<ipython-input-83-92a8092d607c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['PRIMA_RECIBO'] = dfs1['PRIMA_RECIBO'].astype(str).copy()

                       KEY    SSEGURO PRIMA_RECIBO_p PRIMA_RECIBO_s
0      6006870-111-LIBERTY     668744      12.824324          12.82
1        6013563-9-LIBERTY     489217      26.361111          26.36
2       6014329-19-LIBERTY     789926      22.829936          22.83
3        6014916-2-LIBERTY     467783      20.683333          20.68
4        6016183-6-LIBERTY     477975       8.644736          8.645
...                    ...        ...            ...            ...
67206    6142160-1-LIBERTY    1129562      19.137568          19.19
67207   61421608-1-LIBERTY  906439077      12.989999          12.99
67208    6142163-1-LIBERTY    1192579       2.495527          2.496
67209   61421638-1-LIBERTY  906439107      15.369999          15.37
67210   61421658-1-LIBERTY  906439127      21.749999          21.75

[66119 rows x 4 columns]

In [84]:
### PRIMA_RECIBO_FINAL

dfp1 = dfp[['KEY', 'SSEGURO', 'PRIMA_RECIBO_FINAL']]
dfs1 = dfs[['KEY', 'PRIMA_RECIBO_FINAL']]

dfp1['PRIMA_RECIBO_FINAL'] = dfp1['PRIMA_RECIBO_FINAL'].astype(str).copy()
dfs1['PRIMA_RECIBO_FINAL'] = dfs1['PRIMA_RECIBO_FINAL'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.PRIMA_RECIBO_FINAL_p != dfm.PRIMA_RECIBO_FINAL_s) & (~dfm.PRIMA_RECIBO_FINAL_s.isnull()) & (~dfm.PRIMA_RECIBO_FINAL_p.isnull())].copy()
dfm1[['KEY','SSEGURO','PRIMA_RECIBO_FINAL_p','PRIMA_RECIBO_FINAL_s']]

<ipython-input-84-016fa39b0f2f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['PRIMA_RECIBO_FINAL'] = dfp1['PRIMA_RECIBO_FINAL'].astype(str).copy()
<ipython-input-84-016fa39b0f2f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['PRIMA_RECIBO_FINAL'] = dfs1['PRIMA_RECIBO_FINAL'].astype(str).copy()

,KEY,SSEGURO,PRIMA_RECIBO_FINAL_p,PRIMA_RECIBO_FINAL_s
0,6006870-111-LIBERTY,668744,6.412162,6.412
1,6013563-9-LIBERTY,489217,26.361111,26.36
2,6014329-19-LIBERTY,789926,22.829936,22.83
3,6014916-2-LIBERTY,467783,20.683333,20.68
4,6016183-6-LIBERTY,477975,8.644736,8.645
...,...,...,...,...
67185,61421335-1-LIBERTY,906438795,5.0,5
67197,6142149-1-LIBERTY,1192412,12.0,12
67200,61421522-1-LIBERTY,906438988,0.0,0
67207,61421608-1-LIBERTY,906439077,0.0,0
67208,6142163-1-LIBERTY,1192579,0.0,0

In [85]:
### COB_INI

dfp1 = dfp[['KEY', 'SSEGURO', 'COB_INI']]
dfs1 = dfs[['KEY', 'COB_INI']]

dfp1['COB_INI'] = dfp1['COB_INI'].astype(str).copy()
dfs1['COB_INI'] = dfs1['COB_INI'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COB_INI_p != dfm.COB_INI_s) & (~dfm.COB_INI_s.isnull()) & (~dfm.COB_INI_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COB_INI_p','COB_INI_s']]

<ipython-input-85-a8d82fec7a7f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COB_INI'] = dfp1['COB_INI'].astype(str).copy()
<ipython-input-85-a8d82fec7a7f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COB_INI'] = dfs1['COB_INI'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, COB_INI_p, COB_INI_s]
Index: []

In [86]:
### COB_FIN

dfp1 = dfp[['KEY', 'SSEGURO', 'COB_FIN']]
dfs1 = dfs[['KEY', 'COB_FIN']]

dfp1['COB_FIN'] = dfp1['COB_FIN'].astype(str).copy()
dfs1['COB_FIN'] = dfs1['COB_FIN'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COB_FIN_p != dfm.COB_FIN_s) & (~dfm.COB_FIN_s.isnull()) & (~dfm.COB_FIN_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COB_FIN_p','COB_FIN_s']]

<ipython-input-86-c27e3acd69c9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COB_FIN'] = dfp1['COB_FIN'].astype(str).copy()
<ipython-input-86-c27e3acd69c9>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COB_FIN'] = dfs1['COB_FIN'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, COB_FIN_p, COB_FIN_s]
Index: []

In [87]:
### FECHA_COTRENOV

dfp1 = dfp[['KEY', 'SSEGURO', 'FECHA_COTRENOV']]
dfs1 = dfs[['KEY', 'FECHA_COTRENOV']]

dfp1['FECHA_COTRENOV'] = dfp1['FECHA_COTRENOV'].astype(str).copy()
dfs1['FECHA_COTRENOV'] = dfs1['FECHA_COTRENOV'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FECHA_COTRENOV_p != dfm.FECHA_COTRENOV_s) & (~dfm.FECHA_COTRENOV_s.isnull()) & (~dfm.FECHA_COTRENOV_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FECHA_COTRENOV_p','FECHA_COTRENOV_s']]

<ipython-input-87-c8082b4be497>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FECHA_COTRENOV'] = dfp1['FECHA_COTRENOV'].astype(str).copy()
<ipython-input-87-c8082b4be497>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FECHA_COTRENOV'] = dfs1['FECHA_COTRENOV'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, FECHA_COTRENOV_p, FECHA_COTRENOV_s]
Index: []

In [88]:
### PLAN_DESC

dfp1 = dfp[['KEY', 'SSEGURO', 'PLAN_DESC']]
dfs1 = dfs[['KEY', 'PLAN_DESC']]

dfp1['PLAN_DESC'] = dfp1['PLAN_DESC'].astype(str).copy()
dfs1['PLAN_DESC'] = dfs1['PLAN_DESC'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.PLAN_DESC_p != dfm.PLAN_DESC_s) & (~dfm.PLAN_DESC_s.isnull()) & (~dfm.PLAN_DESC_p.isnull())].copy()
dfm1[['KEY','SSEGURO','PLAN_DESC_p','PLAN_DESC_s']]

<ipython-input-88-661768cece28>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['PLAN_DESC'] = dfp1['PLAN_DESC'].astype(str).copy()
<ipython-input-88-661768cece28>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['PLAN_DESC'] = dfs1['PLAN_DESC'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, PLAN_DESC_p, PLAN_DESC_s]
Index: []

In [89]:
### TIPO_PLAN

dfp1 = dfp[['KEY', 'SSEGURO', 'TIPO_PLAN']]
dfs1 = dfs[['KEY', 'TIPO_PLAN']]

dfp1['TIPO_PLAN'] = dfp1['TIPO_PLAN'].astype(str).copy()
dfs1['TIPO_PLAN'] = dfs1['TIPO_PLAN'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.TIPO_PLAN_p != dfm.TIPO_PLAN_s) & (~dfm.TIPO_PLAN_s.isnull()) & (~dfm.TIPO_PLAN_p.isnull())].copy()
dfm1[['KEY','SSEGURO','TIPO_PLAN_p','TIPO_PLAN_s']]

<ipython-input-89-6d3d7a5b80d9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['TIPO_PLAN'] = dfp1['TIPO_PLAN'].astype(str).copy()
<ipython-input-89-6d3d7a5b80d9>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['TIPO_PLAN'] = dfs1['TIPO_PLAN'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, TIPO_PLAN_p, TIPO_PLAN_s]
Index: []

In [90]:
### ANTERIOR

dfp1 = dfp[['KEY', 'SSEGURO', 'ANTERIOR']]
dfs1 = dfs[['KEY', 'ANTERIOR']]

dfp1['ANTERIOR'] = dfp1['ANTERIOR'].astype(str).copy()
dfs1['ANTERIOR'] = dfs1['ANTERIOR'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.ANTERIOR_p != dfm.ANTERIOR_s) & (~dfm.ANTERIOR_s.isnull()) & (~dfm.ANTERIOR_p.isnull())].copy()
dfm1[['KEY','SSEGURO','ANTERIOR_p','ANTERIOR_s']]

<ipython-input-90-1fd5b1608581>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['ANTERIOR'] = dfp1['ANTERIOR'].astype(str).copy()
<ipython-input-90-1fd5b1608581>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['ANTERIOR'] = dfs1['ANTERIOR'].astype(str).copy()

                       KEY    SSEGURO ANTERIOR_p ANTERIOR_s
54       6035900-4-LIBERTY     809036   EX PENTA         NO
70       6038454-2-LIBERTY     555399   EX PENTA         NO
71       6038618-2-LIBERTY     521777   EX PENTA         NO
90     6040630-123-LIBERTY     555580   EX PENTA         NO
93       6040993-2-LIBERTY     491381         NO   EX PENTA
...                    ...        ...        ...        ...
67053   61420152-1-LIBERTY  906433596   EX PENTA         NO
67055   61420176-2-LIBERTY  906433779   EX PENTA         NO
67101   61420559-1-LIBERTY  906363767   EX PENTA         NO
67121   61420752-1-LIBERTY  906436578   EX PENTA         NO
67131   61420840-1-LIBERTY  906358743   EX PENTA         NO

[5709 rows x 4 columns]

In [91]:
### NUM_ITEMS

dfp1 = dfp[['KEY', 'SSEGURO', 'NUM_ITEMS']]
dfs1 = dfs[['KEY', 'NUM_ITEMS']]

dfp1['NUM_ITEMS'] = dfp1['NUM_ITEMS'].astype(str).copy()
dfs1['NUM_ITEMS'] = dfs1['NUM_ITEMS'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.NUM_ITEMS_p != dfm.NUM_ITEMS_s) & (~dfm.NUM_ITEMS_s.isnull()) & (~dfm.NUM_ITEMS_p.isnull())].copy()
dfm1[['KEY','SSEGURO','NUM_ITEMS_p','NUM_ITEMS_s']]

<ipython-input-91-fdda43fcb98b>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['NUM_ITEMS'] = dfp1['NUM_ITEMS'].astype(str).copy()
<ipython-input-91-fdda43fcb98b>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['NUM_ITEMS'] = dfs1['NUM_ITEMS'].astype(str).copy()

                         KEY    SSEGURO NUM_ITEMS_p NUM_ITEMS_s
34602    61185197-10-LIBERTY  904343644        1157        1152
34603  61185197-1007-LIBERTY  907313098        1157        1152
34604  61185197-1018-LIBERTY  907313166        1157        1152
34605  61185197-1024-LIBERTY  907313194        1157        1152
34606  61185197-1060-LIBERTY  907313418        1157        1152
...                      ...        ...         ...         ...
63252    61386347-77-LIBERTY  906198584         262         260
63253    61386347-80-LIBERTY  906198591         262         260
63254    61386347-83-LIBERTY  906239785         262         260
63255    61386347-85-LIBERTY  906240122         262         260
63256    61386347-96-LIBERTY  906240139         262         260

[367 rows x 4 columns]

In [92]:
### COD_MARCA_P

dfp1 = dfp[['KEY', 'SSEGURO', 'COD_MARCA_P']]
dfs1 = dfs[['KEY', 'COD_MARCA_P']]

dfp1['COD_MARCA_P'] = dfp1['COD_MARCA_P'].astype(str).copy()
dfs1['COD_MARCA_P'] = dfs1['COD_MARCA_P'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COD_MARCA_P_p != dfm.COD_MARCA_P_s) & (~dfm.COD_MARCA_P_s.isnull()) & (~dfm.COD_MARCA_P_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COD_MARCA_P_p','COD_MARCA_P_s']]

<ipython-input-92-9e5ac4d95c2e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COD_MARCA_P'] = dfp1['COD_MARCA_P'].astype(str).copy()
<ipython-input-92-9e5ac4d95c2e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COD_MARCA_P'] = dfs1['COD_MARCA_P'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, COD_MARCA_P_p, COD_MARCA_P_s]
Index: []

In [93]:
### COD_MODELO_P

dfp1 = dfp[['KEY', 'SSEGURO', 'COD_MODELO_P']]
dfs1 = dfs[['KEY', 'COD_MODELO_P']]

dfp1['COD_MODELO_P'] = dfp1['COD_MODELO_P'].astype(str).copy()
dfs1['COD_MODELO_P'] = dfs1['COD_MODELO_P'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COD_MODELO_P_p != dfm.COD_MODELO_P_s) & (~dfm.COD_MODELO_P_s.isnull()) & (~dfm.COD_MODELO_P_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COD_MODELO_P_p','COD_MODELO_P_s']]

<ipython-input-93-9268faadfb6e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COD_MODELO_P'] = dfp1['COD_MODELO_P'].astype(str).copy()
<ipython-input-93-9268faadfb6e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COD_MODELO_P'] = dfs1['COD_MODELO_P'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, COD_MODELO_P_p, COD_MODELO_P_s]
Index: []

In [94]:
### COD_TIPO_P

dfp1 = dfp[['KEY', 'SSEGURO', 'COD_TIPO_P']]
dfs1 = dfs[['KEY', 'COD_TIPO_P']]

dfp1['COD_TIPO_P'] = dfp1['COD_TIPO_P'].astype(str).copy()
dfs1['COD_TIPO_P'] = dfs1['COD_TIPO_P'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.COD_TIPO_P_p != dfm.COD_TIPO_P_s) & (~dfm.COD_TIPO_P_s.isnull()) & (~dfm.COD_TIPO_P_p.isnull())].copy()
dfm1[['KEY','SSEGURO','COD_TIPO_P_p','COD_TIPO_P_s']]

<ipython-input-94-83f9ead3c726>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['COD_TIPO_P'] = dfp1['COD_TIPO_P'].astype(str).copy()
<ipython-input-94-83f9ead3c726>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['COD_TIPO_P'] = dfs1['COD_TIPO_P'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, COD_TIPO_P_p, COD_TIPO_P_s]
Index: []

In [95]:
### CANAL

dfp1 = dfp[['KEY', 'SSEGURO', 'CANAL']]
dfs1 = dfs[['KEY', 'CANAL']]

dfp1['CANAL'] = dfp1['CANAL'].astype(str).copy()
dfs1['CANAL'] = dfs1['CANAL'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.CANAL_p != dfm.CANAL_s) & (~dfm.CANAL_s.isnull()) & (~dfm.CANAL_p.isnull())].copy()
dfm1[['KEY','SSEGURO','CANAL_p','CANAL_s']]

<ipython-input-95-d58e63eb3db5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['CANAL'] = dfp1['CANAL'].astype(str).copy()
<ipython-input-95-d58e63eb3db5>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['CANAL'] = dfs1['CANAL'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, CANAL_p, CANAL_s]
Index: []

In [96]:
### DURACION_PLAN

dfp1 = dfp[['KEY', 'SSEGURO', 'DURACION_PLAN']]
dfs1 = dfs[['KEY', 'DURACION_PLAN']]

dfp1['DURACION_PLAN'] = dfp1['DURACION_PLAN'].astype(str).copy()
dfs1['DURACION_PLAN'] = dfs1['DURACION_PLAN'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.DURACION_PLAN_p != dfm.DURACION_PLAN_s) & (~dfm.DURACION_PLAN_s.isnull()) & (~dfm.DURACION_PLAN_p.isnull())].copy()
dfm1[['KEY','SSEGURO','DURACION_PLAN_p','DURACION_PLAN_s']]

<ipython-input-96-281c563b18ea>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['DURACION_PLAN'] = dfp1['DURACION_PLAN'].astype(str).copy()
<ipython-input-96-281c563b18ea>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['DURACION_PLAN'] = dfs1['DURACION_PLAN'].astype(str).copy()

                       KEY    SSEGURO   DURACION_PLAN_p DURACION_PLAN_s
153    6049507-350-LIBERTY     571163  ENTRE 1 Y 2 ANOS           1 ANO
154    6049507-362-LIBERTY     817363  ENTRE 1 Y 2 ANOS           1 ANO
155    6049507-366-LIBERTY     827708  ENTRE 1 Y 2 ANOS           1 ANO
156    6049507-379-LIBERTY     828250  ENTRE 1 Y 2 ANOS           1 ANO
157    6049507-382-LIBERTY    1328247       MENOS 1 ANO           1 ANO
...                    ...        ...               ...             ...
66442   61414599-1-LIBERTY  906381209       MENOS 1 ANO           1 ANO
66476   61414871-1-LIBERTY  906382689       MENOS 1 ANO           1 ANO
66592    6141577-2-LIBERTY    1458074       MENOS 1 ANO           1 ANO
66722    6141677-4-LIBERTY    1740826       MENOS 1 ANO           1 ANO
66782    6141741-2-LIBERTY    1581080       MENOS 1 ANO           1 ANO

[1861 rows x 4 columns]

In [97]:
### ORIGEN_MARCA

dfp1 = dfp[['KEY', 'SSEGURO', 'ORIGEN_MARCA']]
dfs1 = dfs[['KEY', 'ORIGEN_MARCA']]

dfp1['ORIGEN_MARCA'] = dfp1['ORIGEN_MARCA'].astype(str).copy()
dfs1['ORIGEN_MARCA'] = dfs1['ORIGEN_MARCA'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.ORIGEN_MARCA_p != dfm.ORIGEN_MARCA_s) & (~dfm.ORIGEN_MARCA_s.isnull()) & (~dfm.ORIGEN_MARCA_p.isnull())].copy()
dfm1[['KEY','SSEGURO','ORIGEN_MARCA_p','ORIGEN_MARCA_s']]

<ipython-input-97-a88a1d697192>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['ORIGEN_MARCA'] = dfp1['ORIGEN_MARCA'].astype(str).copy()
<ipython-input-97-a88a1d697192>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['ORIGEN_MARCA'] = dfs1['ORIGEN_MARCA'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, ORIGEN_MARCA_p, ORIGEN_MARCA_s]
Index: []

In [98]:
### ANTIG_VEHICULO

dfp1 = dfp[['KEY', 'SSEGURO', 'ANTIG_VEHICULO']]
dfs1 = dfs[['KEY', 'ANTIG_VEHICULO']]

dfp1['ANTIG_VEHICULO'] = dfp1['ANTIG_VEHICULO'].astype(str).copy()
dfs1['ANTIG_VEHICULO'] = dfs1['ANTIG_VEHICULO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.ANTIG_VEHICULO_p != dfm.ANTIG_VEHICULO_s) & (~dfm.ANTIG_VEHICULO_s.isnull()) & (~dfm.ANTIG_VEHICULO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','ANTIG_VEHICULO_p','ANTIG_VEHICULO_s']]

<ipython-input-98-3f39a971544d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['ANTIG_VEHICULO'] = dfp1['ANTIG_VEHICULO'].astype(str).copy()
<ipython-input-98-3f39a971544d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['ANTIG_VEHICULO'] = dfs1['ANTIG_VEHICULO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, ANTIG_VEHICULO_p, ANTIG_VEHICULO_s]
Index: []

In [99]:
### PT_RO

dfp1 = dfp[['KEY', 'SSEGURO', 'PT_RO']]
dfs1 = dfs[['KEY', 'PT_RO']]

dfp1['PT_RO'] = dfp1['PT_RO'].astype(str).copy()
dfs1['PT_RO'] = dfs1['PT_RO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.PT_RO_p != dfm.PT_RO_s) & (~dfm.PT_RO_s.isnull()) & (~dfm.PT_RO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','PT_RO_p','PT_RO_s']]

<ipython-input-99-f5588a606ff4>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['PT_RO'] = dfp1['PT_RO'].astype(str).copy()
<ipython-input-99-f5588a606ff4>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['PT_RO'] = dfs1['PT_RO'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, PT_RO_p, PT_RO_s]
Index: []

In [100]:
### DATE_UPDATE

dfp1 = dfp[['KEY', 'SSEGURO', 'DATE_UPDATE']]
dfs1 = dfs[['KEY', 'DATE_UPDATE']]

dfp1['DATE_UPDATE'] = dfp1['DATE_UPDATE'].astype(str).copy()
dfs1['DATE_UPDATE'] = dfs1['DATE_UPDATE'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.DATE_UPDATE_p != dfm.DATE_UPDATE_s) & (~dfm.DATE_UPDATE_s.isnull()) & (~dfm.DATE_UPDATE_p.isnull())].copy()
dfm1[['KEY','SSEGURO','DATE_UPDATE_p','DATE_UPDATE_s']]

<ipython-input-100-63c32d97f4aa>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['DATE_UPDATE'] = dfp1['DATE_UPDATE'].astype(str).copy()
<ipython-input-100-63c32d97f4aa>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['DATE_UPDATE'] = dfs1['DATE_UPDATE'].astype(str).copy()

                       KEY    SSEGURO DATE_UPDATE_p DATE_UPDATE_s
0      6006870-111-LIBERTY     668744    2022-06-14    2022-06-05
1        6013563-9-LIBERTY     489217    2022-06-14    2022-06-05
2       6014329-19-LIBERTY     789926    2022-06-14    2022-06-05
3        6014916-2-LIBERTY     467783    2022-06-14    2022-06-05
4        6016183-6-LIBERTY     477975    2022-06-14    2022-06-05
...                    ...        ...           ...           ...
67206    6142160-1-LIBERTY    1129562    2022-06-14    2022-06-05
67207   61421608-1-LIBERTY  906439077    2022-06-14    2022-06-05
67208    6142163-1-LIBERTY    1192579    2022-06-14    2022-06-05
67209   61421638-1-LIBERTY  906439107    2022-06-14    2022-06-05
67210   61421658-1-LIBERTY  906439127    2022-06-14    2022-06-05

[67211 rows x 4 columns]

In [101]:
### FORMA_PAGO_INI

dfp1 = dfp[['KEY', 'SSEGURO', 'FORMA_PAGO_INI']]
dfs1 = dfs[['KEY', 'FORMA_PAGO_INI']]

dfp1['FORMA_PAGO_INI'] = dfp1['FORMA_PAGO_INI'].astype(str).copy()
dfs1['FORMA_PAGO_INI'] = dfs1['FORMA_PAGO_INI'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FORMA_PAGO_INI_p != dfm.FORMA_PAGO_INI_s) & (~dfm.FORMA_PAGO_INI_s.isnull()) & (~dfm.FORMA_PAGO_INI_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FORMA_PAGO_INI_p','FORMA_PAGO_INI_s']]

<ipython-input-101-7d8fbb6d6991>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FORMA_PAGO_INI'] = dfp1['FORMA_PAGO_INI'].astype(str).copy()
<ipython-input-101-7d8fbb6d6991>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FORMA_PAGO_INI'] = dfs1['FORMA_PAGO_INI'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, FORMA_PAGO_INI_p, FORMA_PAGO_INI_s]
Index: []

In [102]:
### FORMA_PAGO_FIN

dfp1 = dfp[['KEY', 'SSEGURO', 'FORMA_PAGO_FIN']]
dfs1 = dfs[['KEY', 'FORMA_PAGO_FIN']]

dfp1['FORMA_PAGO_FIN'] = dfp1['FORMA_PAGO_FIN'].astype(str).copy()
dfs1['FORMA_PAGO_FIN'] = dfs1['FORMA_PAGO_FIN'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FORMA_PAGO_FIN_p != dfm.FORMA_PAGO_FIN_s) & (~dfm.FORMA_PAGO_FIN_s.isnull()) & (~dfm.FORMA_PAGO_FIN_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FORMA_PAGO_FIN_p','FORMA_PAGO_FIN_s']]

<ipython-input-102-936af960e696>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FORMA_PAGO_FIN'] = dfp1['FORMA_PAGO_FIN'].astype(str).copy()
<ipython-input-102-936af960e696>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FORMA_PAGO_FIN'] = dfs1['FORMA_PAGO_FIN'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, FORMA_PAGO_FIN_p, FORMA_PAGO_FIN_s]
Index: []

In [103]:
### METODO_PAGO

dfp1 = dfp[['KEY', 'SSEGURO', 'METODO_PAGO']]
dfs1 = dfs[['KEY', 'METODO_PAGO']]

dfp1['METODO_PAGO'] = dfp1['METODO_PAGO'].astype(str).copy()
dfs1['METODO_PAGO'] = dfs1['METODO_PAGO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.METODO_PAGO_p != dfm.METODO_PAGO_s) & (~dfm.METODO_PAGO_s.isnull()) & (~dfm.METODO_PAGO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','METODO_PAGO_p','METODO_PAGO_s']]

<ipython-input-103-4b66a5fc6cef>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['METODO_PAGO'] = dfp1['METODO_PAGO'].astype(str).copy()
<ipython-input-103-4b66a5fc6cef>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['METODO_PAGO'] = dfs1['METODO_PAGO'].astype(str).copy()

                      KEY    SSEGURO METODO_PAGO_p METODO_PAGO_s
1       6013563-9-LIBERTY     489217           nan      CUPONERA
16      6025546-3-LIBERTY     586519           nan  PAGO CONTADO
17     6026427-15-LIBERTY     541410           nan  PAGO CONTADO
18     6026427-16-LIBERTY     541412           nan  PAGO CONTADO
21      6026905-5-LIBERTY     569006           nan  PAGO CONTADO
...                   ...        ...           ...           ...
65920  61410102-1-LIBERTY  906341996           nan           PAT
65921  61410104-1-LIBERTY  906342000           nan           PAT
65923  61410110-1-LIBERTY  906342010           nan           PAT
66409  61414294-1-LIBERTY  906380138           nan           PAT
67078  61420388-1-LIBERTY  906435021           nan           PAT

[570 rows x 4 columns]

In [104]:
### RAZON_CUOTAS

dfp1 = dfp[['KEY', 'SSEGURO', 'RAZON_CUOTAS']]
dfs1 = dfs[['KEY', 'RAZON_CUOTAS']]

dfp1['RAZON_CUOTAS'] = dfp1['RAZON_CUOTAS'].astype(str).copy()
dfs1['RAZON_CUOTAS'] = dfs1['RAZON_CUOTAS'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.RAZON_CUOTAS_p != dfm.RAZON_CUOTAS_s) & (~dfm.RAZON_CUOTAS_s.isnull()) & (~dfm.RAZON_CUOTAS_p.isnull())].copy()
dfm1[['KEY','SSEGURO','RAZON_CUOTAS_p','RAZON_CUOTAS_s']]

<ipython-input-104-0241036f438d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['RAZON_CUOTAS'] = dfp1['RAZON_CUOTAS'].astype(str).copy()
<ipython-input-104-0241036f438d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['RAZON_CUOTAS'] = dfs1['RAZON_CUOTAS'].astype(str).copy()

                      KEY  SSEGURO   RAZON_CUOTAS_p         RAZON_CUOTAS_s
2      6014329-19-LIBERTY   789926  Redocumentación        Redocumentacion
7       6021077-2-LIBERTY   581703  Redocumentación        Redocumentacion
16      6025546-3-LIBERTY   586519              nan  Cuotas impagas manual
22     6027603-40-LIBERTY   583019              nan         Cuotas impagas
30      6030489-2-LIBERTY   590155  Redocumentación        Redocumentacion
...                   ...      ...              ...                    ...
67183   6142125-1-LIBERTY  1126412  Redocumentación        Redocumentacion
67197   6142149-1-LIBERTY  1192412  Redocumentación        Redocumentacion
67201   6142153-1-LIBERTY  1192429  Redocumentación        Redocumentacion
67206   6142160-1-LIBERTY  1129562  Redocumentación        Redocumentacion
67208   6142163-1-LIBERTY  1192579  Redocumentación        Redocumentacion

[11815 rows x 4 columns]

In [105]:
### TUVO_PT

dfp1 = dfp[['KEY', 'SSEGURO', 'TUVO_PT']]
dfs1 = dfs[['KEY', 'TUVO_PT']]

dfp1['TUVO_PT'] = dfp1['TUVO_PT'].astype(str).copy()
dfs1['TUVO_PT'] = dfs1['TUVO_PT'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.TUVO_PT_p != dfm.TUVO_PT_s) & (~dfm.TUVO_PT_s.isnull()) & (~dfm.TUVO_PT_p.isnull())].copy()
dfm1[['KEY','SSEGURO','TUVO_PT_p','TUVO_PT_s']]

<ipython-input-105-4603868c9eb6>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['TUVO_PT'] = dfp1['TUVO_PT'].astype(str).copy()
<ipython-input-105-4603868c9eb6>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['TUVO_PT'] = dfs1['TUVO_PT'].astype(str).copy()

                        KEY    SSEGURO TUVO_PT_p TUVO_PT_s
429    6063061-1468-LIBERTY     584622       nan         1
538    6063061-2356-LIBERTY     766423       nan         1
562    6063061-2496-LIBERTY     823739       nan         1
726    6063062-1012-LIBERTY     470342       nan         1
828    6063062-2488-LIBERTY     535832       nan         1
...                     ...        ...       ...       ...
65607    61407087-1-LIBERTY  906323203       nan         1
66198    61412616-1-LIBERTY  906275764       nan         1
66447     6141468-1-LIBERTY    1185898       nan         1
66595    61415785-1-LIBERTY  906391117       nan         1
66732     6141689-1-LIBERTY    1188937       nan         1

[223 rows x 4 columns]

In [106]:
### FORMA_PAGO_DEF

dfp1 = dfp[['KEY', 'SSEGURO', 'FORMA_PAGO_DEF']]
dfs1 = dfs[['KEY', 'FORMA_PAGO_DEF']]

dfp1['FORMA_PAGO_DEF'] = dfp1['FORMA_PAGO_DEF'].astype(str).copy()
dfs1['FORMA_PAGO_DEF'] = dfs1['FORMA_PAGO_DEF'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FORMA_PAGO_DEF_p != dfm.FORMA_PAGO_DEF_s) & (~dfm.FORMA_PAGO_DEF_s.isnull()) & (~dfm.FORMA_PAGO_DEF_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FORMA_PAGO_DEF_p','FORMA_PAGO_DEF_s']]

<ipython-input-106-463708e2cba3>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FORMA_PAGO_DEF'] = dfp1['FORMA_PAGO_DEF'].astype(str).copy()
<ipython-input-106-463708e2cba3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FORMA_PAGO_DEF'] = dfs1['FORMA_PAGO_DEF'].astype(str).copy()

                      KEY    SSEGURO FORMA_PAGO_DEF_p FORMA_PAGO_DEF_s
2061    6068105-1-LIBERTY     438933     PAGO CONTADO      AVISO CUOTA
2228    6069715-3-LIBERTY     549889     PAGO CONTADO         CUPONERA
2800    6072751-1-LIBERTY     487693         CUPONERA              PAC
2820    6072786-1-LIBERTY     487874      AVISO CUOTA              PAC
3296    6075060-1-LIBERTY     528454      AVISO CUOTA              PAC
3742    6077012-1-LIBERTY     547910      AVISO CUOTA              PAC
4902    6081956-1-LIBERTY     585658     PAGO CONTADO      AVISO CUOTA
6738    6086576-1-LIBERTY     623594              PAT         CUPONERA
7733    6091566-1-LIBERTY     668199      AVISO CUOTA         CUPONERA
8774    6095914-1-LIBERTY     703769      AVISO CUOTA              PAC
8861    6096350-1-LIBERTY     707370      AVISO CUOTA         CUPONERA
9149    6097288-2-LIBERTY     716031     PAGO CONTADO      AVISO CUOTA
11439   6100875-1-LIBERTY     727454      AVISO CUOTA              PAC
12414   6101653-1-LIBERTY     765798         CUPONERA              PAC
12991   6102149-1-LIBERTY     771473         CUPONERA              PAT
13328  61024279-1-LIBERTY  900145403              PAC      AVISO CUOTA
16456   6103519-1-LIBERTY     773497      AVISO CUOTA         CUPONERA
16890   6103869-2-LIBERTY    1031856      AVISO CUOTA              PAC
17099   6104014-1-LIBERTY     774887      AVISO CUOTA         CUPONERA
17183   6104079-1-LIBERTY     774968      AVISO CUOTA              PAC
17486   6104277-1-LIBERTY     775245      AVISO CUOTA         CUPONERA
19065  61058095-1-LIBERTY  900598709     PAGO CONTADO      AVISO CUOTA
19803   6106493-1-LIBERTY     778372     PAGO CONTADO         CUPONERA
20317   6106785-1-LIBERTY     800088     PAGO CONTADO      AVISO CUOTA
23086   6109046-1-LIBERTY     823158              PAT         CUPONERA
24142  61099561-1-LIBERTY  902947414     PAGO CONTADO              PAT
26113   6111564-1-LIBERTY     856710              PAT         CUPONERA
26736  61120072-1-LIBERTY  903484597      AVISO CUOTA         CUPONERA
26930  61121868-1-LIBERTY  903246517         CUPONERA              PAC
28375   6113420-1-LIBERTY     884667              PAC      AVISO CUOTA
29929   6114629-1-LIBERTY     879757     PAGO CONTADO      AVISO CUOTA
31927  61164029-1-LIBERTY  903992576     PAGO CONTADO      AVISO CUOTA
32027   6116475-1-LIBERTY     913159      AVISO CUOTA              PAC
32164  61165882-1-LIBERTY  904024329     PAGO CONTADO              PAC
32834   6117337-1-LIBERTY     881793     PAGO CONTADO         CUPONERA
34411   6118447-1-LIBERTY     882637     PAGO CONTADO              PAC
35554  61189147-1-LIBERTY  904326552     PAGO CONTADO              PAC
38361   6121316-1-LIBERTY     923600      AVISO CUOTA         CUPONERA
38410  61213552-1-LIBERTY  904538819      AVISO CUOTA              PAC
38960  61218644-1-LIBERTY  904535137      AVISO CUOTA              PAC
39654  61223864-1-LIBERTY  904653081      AVISO CUOTA         CUPONERA
43245  61244443-1-LIBERTY  904891784      AVISO CUOTA              PAT
43451  61246509-1-LIBERTY  904796708      AVISO CUOTA              PAC
46698  61269836-1-LIBERTY  905083616      AVISO CUOTA     PAGO CONTADO
47169   6127291-2-LIBERTY     923864      AVISO CUOTA         CUPONERA
47333   6127420-1-LIBERTY     968038      AVISO CUOTA         CUPONERA
48878   6128477-1-LIBERTY     965237      AVISO CUOTA              PAC
51930   6130842-1-LIBERTY    1033809      AVISO CUOTA              PAC
61188   6136740-1-LIBERTY    1124393      AVISO CUOTA         CUPONERA

### MOTIVO_CANCEL_ANUL

dfp1 = dfp[['KEY', 'SSEGURO', 'MOTIVO_CANCEL_ANUL']]
dfs1 = dfs[['KEY', 'MOTIVO_CANCEL_ANUL']]

dfp1['MOTIVO_CANCEL_ANUL'] = dfp1['MOTIVO_CANCEL_ANUL'].astype(str).copy()
dfs1['MOTIVO_CANCEL_ANUL'] = dfs1['MOTIVO_CANCEL_ANUL'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.MOTIVO_CANCEL_ANUL_p != dfm.MOTIVO_CANCEL_ANUL_s) & (~dfm.MOTIVO_CANCEL_ANUL_s.isnull()) & (~dfm.MOTIVO_CANCEL_ANUL_p.isnull())].copy()
dfm1[['KEY','SSEGURO','MOTIVO_CANCEL_ANUL_p','MOTIVO_CANCEL_ANUL_s']]

In [107]:
### TIPO_PERS

dfp1 = dfp[['KEY', 'SSEGURO', 'TIPO_PERS']]
dfs1 = dfs[['KEY', 'TIPO_PERS']]

dfp1['TIPO_PERS'] = dfp1['TIPO_PERS'].astype(str).copy()
dfs1['TIPO_PERS'] = dfs1['TIPO_PERS'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.TIPO_PERS_p != dfm.TIPO_PERS_s) & (~dfm.TIPO_PERS_s.isnull()) & (~dfm.TIPO_PERS_p.isnull())].copy()
dfm1[['KEY','SSEGURO','TIPO_PERS_p','TIPO_PERS_s']]

<ipython-input-107-a5239b28ac26>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['TIPO_PERS'] = dfp1['TIPO_PERS'].astype(str).copy()
<ipython-input-107-a5239b28ac26>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['TIPO_PERS'] = dfs1['TIPO_PERS'].astype(str).copy()

Empty DataFrame
Columns: [KEY, SSEGURO, TIPO_PERS_p, TIPO_PERS_s]
Index: []

In [108]:
### SEXO

dfp1 = dfp[['KEY', 'SSEGURO', 'SEXO']]
dfs1 = dfs[['KEY', 'SEXO']]

dfp1['SEXO'] = dfp1['SEXO'].astype(str).copy()
dfs1['SEXO'] = dfs1['SEXO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.SEXO_p != dfm.SEXO_s) & (~dfm.SEXO_s.isnull()) & (~dfm.SEXO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','SEXO_p','SEXO_s']]

<ipython-input-108-fa3ce129d2cb>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['SEXO'] = dfp1['SEXO'].astype(str).copy()
<ipython-input-108-fa3ce129d2cb>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['SEXO'] = dfs1['SEXO'].astype(str).copy()

                        KEY    SSEGURO SEXO_p SEXO_s
110       6044115-2-LIBERTY     671477      0      1
1054   6063062-4145-LIBERTY     627533      0      1
2064      6068114-2-LIBERTY     945196      1      0
2071      6068137-1-LIBERTY     439339      0      1
2202      6069543-1-LIBERTY     455006      0      1
...                     ...        ...    ...    ...
66631    61416024-1-LIBERTY  906274643      0      1
66812    61417720-1-LIBERTY  906398780    nan      1
66870    61418270-1-LIBERTY  906399348      0      1
66998    61419655-1-LIBERTY  906357364      0      1
67049    61420055-1-LIBERTY  906362847      1      0

[342 rows x 4 columns]

In [109]:
### NACIONALIDAD

dfp1 = dfp[['KEY', 'SSEGURO', 'NACIONALIDAD']]
dfs1 = dfs[['KEY', 'NACIONALIDAD']]

dfp1['NACIONALIDAD'] = dfp1['NACIONALIDAD'].astype(str).copy()
dfs1['NACIONALIDAD'] = dfs1['NACIONALIDAD'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.NACIONALIDAD_p != dfm.NACIONALIDAD_s) & (~dfm.NACIONALIDAD_s.isnull()) & (~dfm.NACIONALIDAD_p.isnull())].copy()
dfm1[['KEY','SSEGURO','NACIONALIDAD_p','NACIONALIDAD_s']]

<ipython-input-109-e4cac2dec1b5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['NACIONALIDAD'] = dfp1['NACIONALIDAD'].astype(str).copy()
<ipython-input-109-e4cac2dec1b5>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['NACIONALIDAD'] = dfs1['NACIONALIDAD'].astype(str).copy()

                        KEY    SSEGURO NACIONALIDAD_p NACIONALIDAD_s
110       6044115-2-LIBERTY     671477            nan              C
1054   6063062-4145-LIBERTY     627533            nan              C
2064      6068114-2-LIBERTY     945196            nan              C
2071      6068137-1-LIBERTY     439339            nan              N
2202      6069543-1-LIBERTY     455006            nan              C
...                     ...        ...            ...            ...
66631    61416024-1-LIBERTY  906274643            nan              C
66812    61417720-1-LIBERTY  906398780            nan              C
66870    61418270-1-LIBERTY  906399348            nan              C
66998    61419655-1-LIBERTY  906357364            nan              C
67049    61420055-1-LIBERTY  906362847            nan              C

[355 rows x 4 columns]

In [110]:
### SEXO_ASEGURADO

dfp1 = dfp[['KEY', 'SSEGURO', 'SEXO_ASEGURADO']]
dfs1 = dfs[['KEY', 'SEXO_ASEGURADO']]

dfp1['SEXO_ASEGURADO'] = dfp1['SEXO_ASEGURADO'].astype(str).copy()
dfs1['SEXO_ASEGURADO'] = dfs1['SEXO_ASEGURADO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.SEXO_ASEGURADO_p != dfm.SEXO_ASEGURADO_s) & (~dfm.SEXO_ASEGURADO_s.isnull()) & (~dfm.SEXO_ASEGURADO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','SEXO_ASEGURADO_p','SEXO_ASEGURADO_s']]

<ipython-input-110-af0a56559c3f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['SEXO_ASEGURADO'] = dfp1['SEXO_ASEGURADO'].astype(str).copy()
<ipython-input-110-af0a56559c3f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['SEXO_ASEGURADO'] = dfs1['SEXO_ASEGURADO'].astype(str).copy()

                        KEY    SSEGURO SEXO_ASEGURADO_p SEXO_ASEGURADO_s
110       6044115-2-LIBERTY     671477                M                F
1054   6063062-4145-LIBERTY     627533                M                F
2064      6068114-2-LIBERTY     945196                F                M
2071      6068137-1-LIBERTY     439339                M                F
2202      6069543-1-LIBERTY     455006                M                F
...                     ...        ...              ...              ...
66631    61416024-1-LIBERTY  906274643                M                F
66812    61417720-1-LIBERTY  906398780              nan                F
66870    61418270-1-LIBERTY  906399348                M                F
66998    61419655-1-LIBERTY  906357364                M                F
67049    61420055-1-LIBERTY  906362847                F                M

[342 rows x 4 columns]

In [111]:
### FECHA_NACIMIENTO

dfp1 = dfp[['KEY', 'SSEGURO', 'FECHA_NACIMIENTO']]
dfs1 = dfs[['KEY', 'FECHA_NACIMIENTO']]

dfp1['FECHA_NACIMIENTO'] = dfp1['FECHA_NACIMIENTO'].astype(str).copy()
dfs1['FECHA_NACIMIENTO'] = dfs1['FECHA_NACIMIENTO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.FECHA_NACIMIENTO_p != dfm.FECHA_NACIMIENTO_s) & (~dfm.FECHA_NACIMIENTO_s.isnull()) & (~dfm.FECHA_NACIMIENTO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','FECHA_NACIMIENTO_p','FECHA_NACIMIENTO_s']]

<ipython-input-111-5927648b4d91>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['FECHA_NACIMIENTO'] = dfp1['FECHA_NACIMIENTO'].astype(str).copy()
<ipython-input-111-5927648b4d91>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['FECHA_NACIMIENTO'] = dfs1['FECHA_NACIMIENTO'].astype(str).copy()

                       KEY    SSEGURO FECHA_NACIMIENTO_p FECHA_NACIMIENTO_s
60       6037639-2-LIBERTY     556915         1945-09-21         1945-09-22
73     6038693-418-LIBERTY     547838         1949-11-02         1949-11-03
74     6038693-421-LIBERTY     575344         1954-11-01         1954-11-02
80     6038693-445-LIBERTY     649953         1944-01-12         1944-01-13
81     6038693-452-LIBERTY     684501         1954-11-01         1954-11-02
...                    ...        ...                ...                ...
67164   61421065-1-LIBERTY  906438354         1945-11-19         1945-11-20
67171   61421139-1-LIBERTY  906438591         1952-06-03         1952-06-04
67178   61421206-1-LIBERTY  906438659         1950-04-01         1950-04-02
67189   61421384-1-LIBERTY  906438846         1954-04-23         1954-04-24
67205   61421585-1-LIBERTY  906439052         1949-05-27         1949-05-28

[7170 rows x 4 columns]

In [112]:
### EDAD_ASEGURADO

dfp1 = dfp[['KEY', 'SSEGURO', 'EDAD_ASEGURADO']]
dfs1 = dfs[['KEY', 'EDAD_ASEGURADO']]

dfp1['EDAD_ASEGURADO'] = dfp1['EDAD_ASEGURADO'].astype(str).copy()
dfs1['EDAD_ASEGURADO'] = dfs1['EDAD_ASEGURADO'].astype(str).copy()

dfm = pd.merge(dfp1, dfs1, how='left',
  left_on=['KEY'],
  right_on=['KEY'],
  left_index=False,
  right_index=False, 
  sort=True,
 suffixes=('_p', '_s'), copy=True, indicator=False,
 validate=None)

dfm1 = dfm.sort_values(['KEY'], ascending=[True])
dfm1 = dfm1.loc[(dfm.EDAD_ASEGURADO_p != dfm.EDAD_ASEGURADO_s) & (~dfm.EDAD_ASEGURADO_s.isnull()) & (~dfm.EDAD_ASEGURADO_p.isnull())].copy()
dfm1[['KEY','SSEGURO','EDAD_ASEGURADO_p','EDAD_ASEGURADO_s']]

<ipython-input-112-f7adde3cede5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfp1['EDAD_ASEGURADO'] = dfp1['EDAD_ASEGURADO'].astype(str).copy()
<ipython-input-112-f7adde3cede5>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs1['EDAD_ASEGURADO'] = dfs1['EDAD_ASEGURADO'].astype(str).copy()

                      KEY    SSEGURO EDAD_ASEGURADO_p EDAD_ASEGURADO_s
2      6014329-19-LIBERTY     789926               70               71
3       6014916-2-LIBERTY     467783               63               64
4       6016183-6-LIBERTY     477975               78               79
7       6021077-2-LIBERTY     581703               57               58
8       6021268-2-LIBERTY     552100               64               65
...                   ...        ...              ...              ...
67194  61421459-1-LIBERTY  906438922               69               68
67197   6142149-1-LIBERTY    1192412               68               69
67199  61421511-1-LIBERTY  906438977               68               67
67200  61421522-1-LIBERTY  906438988               68               67
67206   6142160-1-LIBERTY    1129562               77               78

[15645 rows x 4 columns]